#!/usr/bin/env python3
"""
CNNA Growth Test: tetrahedral boundary orientation closure.

Purpose
-------
The preceding parent-fan plaquette tests found a robust local transverse
noncommutative sector on the three side faces

    (p,c1,c2), (p,c2,c3), (p,c3,c1),

but the sector glued flatly under face-network / double-history tests.  This
script tests the next possible carrier: the full local 3-simplex generated by a
completed parent and its three children,

    T_p = (p,c1,c2,c3),

with oriented boundary

    dT_p = (c1,c2,c3) - (p,c2,c3) + (p,c1,c3) - (p,c1,c2).

The sibling base face (c1,c2,c3) was weak in previous isolated tests.  The gate
here is not whether the base is strong by itself, but whether the complete
oriented tetrahedral boundary carries a residual orientation / chirality /
closure obstruction that is invisible in the three parent-fan faces alone.

No global J, no complex scalar field, no *-algebra, no C*-norm, no GNS and no
AQFT net are introduced.  The only local J diagnostic is the standard audit of
a measured 3x3 skew commutator K=[A_ab,A_bc] on each oriented face.
"""

from __future__ import annotations

import argparse
import math
import random
import shutil
import zipfile
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Tuple

import numpy as np
from scipy.linalg import expm

from record_live_block_base import RealGrowth, LocalCell, build_cells, write_csv

EPS = 1e-12
FACE_LABELS = ("F12", "F23", "F31", "B123")
FAN_LABELS = ("F12", "F23", "F31")


def fro(M: np.ndarray) -> float:
    return float(np.linalg.norm(np.asarray(M, dtype=float), ord="fro"))


def nrm(v: np.ndarray) -> float:
    return float(np.linalg.norm(np.asarray(v, dtype=float).reshape(-1)))


def unit(v: np.ndarray) -> np.ndarray:
    v = np.asarray(v, dtype=float).reshape(-1)
    m = nrm(v)
    return np.zeros_like(v) if m < EPS else v / m


def mean(xs: Iterable[float]) -> float:
    vals = [float(x) for x in xs if np.isfinite(float(x))]
    return float(np.mean(vals)) if vals else float("nan")


def perc(xs: Iterable[float], q: float) -> float:
    vals = [float(x) for x in xs if np.isfinite(float(x))]
    return float(np.percentile(vals, q)) if vals else float("nan")


def skew(M: np.ndarray) -> np.ndarray:
    M = np.asarray(M, dtype=float)
    return 0.5 * (M - M.T)


def sym(M: np.ndarray) -> np.ndarray:
    M = np.asarray(M, dtype=float)
    return 0.5 * (M + M.T)


def rel(A: np.ndarray, B: np.ndarray, signless: bool = False) -> float:
    A = np.asarray(A, dtype=float)
    B = np.asarray(B, dtype=float)
    den = fro(A) + fro(B) + EPS
    if signless:
        return min(fro(A - B), fro(A + B)) / den
    return fro(A - B) / den


def axial_from_skew(K: np.ndarray) -> np.ndarray:
    # K = [[0,-z,y],[z,0,-x],[-y,x,0]] -> (x,y,z)
    K = skew(K)
    return np.array([K[2, 1], K[0, 2], K[1, 0]], dtype=float)


def cosine_abs(a: np.ndarray, b: np.ndarray) -> float:
    na = nrm(a)
    nb = nrm(b)
    if na < EPS or nb < EPS:
        return float("nan")
    return float(abs(np.dot(a.reshape(-1), b.reshape(-1))) / (na * nb + EPS))


def signed_cos(a: np.ndarray, b: np.ndarray) -> float:
    na = nrm(a)
    nb = nrm(b)
    if na < EPS or nb < EPS:
        return float("nan")
    return float(np.dot(a.reshape(-1), b.reshape(-1)) / (na * nb + EPS))


def expm_step(K: np.ndarray, step: float, normalize: bool) -> np.ndarray:
    K = skew(K)
    scale = fro(K) if normalize else 1.0
    if normalize and scale > EPS:
        K = K / scale
    return np.asarray(expm(step * K), dtype=float)


def wilson_product(Ks: List[np.ndarray], step: float, normalize: bool) -> Dict[str, float]:
    if not Ks:
        return {"norm": float("nan"), "skew": float("nan"), "complex": 0, "eig_imag": float("nan"), "det": float("nan")}
    W = np.eye(Ks[0].shape[0])
    # Boundary order is only a diagnostic ordering of the oriented face generators;
    # the gate is comparison to controls, not a claim of continuum Stokes data.
    for K in Ks:
        W = expm_step(K, step, normalize) @ W
    I = np.eye(W.shape[0])
    vals = np.linalg.eigvals(W)
    imag = float(np.max(np.abs(np.imag(vals))))
    return {
        "norm": fro(W - I) / (fro(I) + EPS),
        "skew": fro(skew(W)) / (fro(W) + EPS),
        "complex": int(imag > 1e-8),
        "eig_imag": imag,
        "det": float(np.linalg.det(W)),
    }


def raw_vertex_operator(cell: LocalCell, source_mode: str) -> np.ndarray:
    return sym(cell.matrix_for_source(source_mode))


def reduce_ops(Sa: np.ndarray, Sb: np.ndarray, Sc: np.ndarray, reduction: str) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
    if reduction == "full":
        return Sa, Sb, Sc
    if reduction == "diagonal":
        return np.diag(np.diag(Sa)), np.diag(np.diag(Sb)), np.diag(np.diag(Sc))
    if reduction == "trace_scalar":
        return (
            np.eye(3) * (float(np.trace(Sa)) / 3.0),
            np.eye(3) * (float(np.trace(Sb)) / 3.0),
            np.eye(3) * (float(np.trace(Sc)) / 3.0),
        )
    if reduction == "common_mean_diagonal":
        M = sym((Sa + Sb + Sc) / 3.0)
        _, Q = np.linalg.eigh(M)
        def project(S: np.ndarray) -> np.ndarray:
            return Q @ np.diag(np.diag(Q.T @ S @ Q)) @ Q.T
        return project(Sa), project(Sb), project(Sc)
    raise ValueError(reduction)


@dataclass(frozen=True)
class Tetra:
    kind: str
    parent: int
    level: int
    vertices: Tuple[int, int, int, int]


@dataclass
class FaceObs:
    label: str
    vertices: Tuple[int, int, int]
    K: np.ndarray
    axis: np.ndarray
    J: Optional[np.ndarray]
    P: Optional[np.ndarray]
    omega: float
    K_norm: float
    valid: bool
    J2: float
    leakage: float
    first: float
    edge: float
    complex: int


def local_face(label: str, vertices: Tuple[int, int, int], cells: Dict[int, LocalCell], source_mode: str, reduction: str, min_omega: float) -> FaceObs:
    a, b, c = vertices
    Sa0 = raw_vertex_operator(cells[a], source_mode)
    Sb0 = raw_vertex_operator(cells[b], source_mode)
    Sc0 = raw_vertex_operator(cells[c], source_mode)
    Sa, Sb, Sc = reduce_ops(Sa0, Sb0, Sc0, reduction)
    Aab = Sb - Sa
    Abc = Sc - Sb
    Aca = Sa - Sc
    K = skew(Aab @ Abc - Abc @ Aab)
    vals, vecs = np.linalg.eigh(-K @ K)
    order = np.argsort(vals)[::-1]
    vals = np.maximum(vals[order], 0.0)
    vecs = vecs[:, order]
    omega1 = math.sqrt(float(vals[0])) if vals.size > 0 else 0.0
    omega2 = math.sqrt(float(vals[1])) if vals.size > 1 else 0.0
    omega = 0.5 * (omega1 + omega2)
    K_norm = fro(K)
    axis = axial_from_skew(K)
    eig_imag = float(np.max(np.abs(np.imag(np.linalg.eigvals(K))))) if K_norm > EPS else 0.0
    if omega <= min_omega or omega2 <= min_omega:
        return FaceObs(label, vertices, K, axis, None, None, omega, K_norm, False, float("nan"), float("nan"), fro(Aab + Abc + Aca), mean([fro(Aab), fro(Abc), fro(Aca)]), int(eig_imag > 1e-10))
    U2 = vecs[:, :2]
    P = U2 @ U2.T
    J = K / (omega + EPS)
    I = np.eye(3)
    J2 = fro(P @ (J @ J + P) @ P) / (fro(P) + EPS)
    leakage = fro((I - P) @ J @ P) / (fro(J @ P) + EPS)
    return FaceObs(label, vertices, K, axis, J, P, omega, K_norm, True, J2, leakage, fro(Aab + Abc + Aca), mean([fro(Aab), fro(Abc), fro(Aca)]), int(eig_imag > 1e-10))


def build_model(control: str, max_level: int, mode: str) -> RealGrowth:
    if control == "real_growth":
        model = RealGrowth(mode=mode)
    elif control == "symmetrized_birth":
        model = RealGrowth(mode=mode, growth_rule="symmetrized_birth")
    elif control == "no_backreaction":
        model = RealGrowth(mode=mode, br_ancestor=0.0, br_sibling=0.0)
    else:
        raise ValueError(control)
    model.grow(max_level)
    return model


def build_true_tetras(model: RealGrowth, cells: Dict[int, LocalCell]) -> List[Tetra]:
    out: List[Tetra] = []
    cell_ids = set(cells.keys())
    for p in sorted(model.completed_parent_ids()):
        ch = model.child_ids_ordered(p)
        if len(ch) != 3:
            continue
        c1, c2, c3 = ch
        if p in cell_ids and c1 in cell_ids and c2 in cell_ids and c3 in cell_ids:
            out.append(Tetra("true_tetrahedron", p, int(model.nodes[p].level), (p, c1, c2, c3)))
    return out


def build_random_tetras(model: RealGrowth, cells: Dict[int, LocalCell], count: int, seed: int) -> List[Tetra]:
    rng = random.Random(seed)
    by_level: Dict[int, List[int]] = {}
    for cid, c in cells.items():
        by_level.setdefault(int(c.level), []).append(cid)
    levels = [lv for lv in by_level if lv + 1 in by_level and len(by_level[lv]) >= 1 and len(by_level[lv + 1]) >= 3]
    out: List[Tetra] = []
    attempts = 0
    while levels and len(out) < count and attempts < max(2000, 60 * count):
        attempts += 1
        lv = rng.choice(levels)
        p = rng.choice(by_level[lv])
        cs = rng.sample(by_level[lv + 1], 3)
        # Avoid accidentally selecting the true sibling set.
        true = set(model.child_ids_ordered(p))
        if set(cs) == true:
            continue
        out.append(Tetra("random_tetrahedron", p, lv, (p, cs[0], cs[1], cs[2])))
    return out


def face_sets(t: Tetra) -> Dict[str, Tuple[int, int, int]]:
    p, c1, c2, c3 = t.vertices
    return {
        "F12": (p, c1, c2),
        "F23": (p, c2, c3),
        "F31": (p, c3, c1),
        "B123": (c1, c2, c3),
    }


def summarize_tetra(t: Tetra, cells: Dict[int, LocalCell], source_mode: str, reduction: str, min_omega: float, loop_step: float, identical_clone: bool = False) -> Dict[str, float | int | str]:
    fs = face_sets(t)
    if identical_clone:
        # Replace every vertex in every face by the parent matrix carrier. This is
        # a strict zero-control for any face commutator / boundary chirality.
        p = t.vertices[0]
        fs = {k: (p, p, p) for k in fs}
    obs = {label: local_face(label, verts, cells, source_mode, reduction, min_omega) for label, verts in fs.items()}
    K12, K23, K31, KB = obs["F12"].K, obs["F23"].K, obs["F31"].K, obs["B123"].K

    fan_nat = K12 + K23 + K31
    # Oriented boundary of [p,c1,c2,c3] relative to natural fan labels:
    # B123 - F23 + F13 - F12 = B123 - F23 - F31 - F12.
    boundary = KB - K12 - K23 - K31
    all_norm = obs["B123"].K_norm + obs["F12"].K_norm + obs["F23"].K_norm + obs["F31"].K_norm + EPS
    fan_norm = obs["F12"].K_norm + obs["F23"].K_norm + obs["F31"].K_norm + EPS

    side_axes = [obs[x].axis for x in FAN_LABELS]
    side_norm_axes = [unit(a) for a in side_axes]
    base_axis = obs["B123"].axis
    side_axis_sum = side_axes[0] + side_axes[1] + side_axes[2]
    oriented_axis_boundary = base_axis - side_axis_sum
    side_pair_abs = [cosine_abs(side_axes[i], side_axes[j]) for i, j in [(0,1), (1,2), (2,0)]]
    side_pair_signed = [signed_cos(side_axes[i], side_axes[j]) for i, j in [(0,1), (1,2), (2,0)]]
    if all(nrm(a) > EPS for a in side_axes):
        side_chiral = float(np.linalg.det(np.stack(side_norm_axes, axis=1)))
    else:
        side_chiral = float("nan")
    if nrm(base_axis) > EPS and all(nrm(a) > EPS for a in side_axes[:2]):
        base_side_chiral = float(np.dot(unit(base_axis), np.cross(unit(side_axes[0]), unit(side_axes[1]))))
    else:
        base_side_chiral = float("nan")
    if nrm(base_axis) > EPS and nrm(side_axis_sum) > EPS:
        base_to_side_abs = cosine_abs(base_axis, side_axis_sum)
        base_to_side_signed = signed_cos(base_axis, side_axis_sum)
    else:
        base_to_side_abs = float("nan")
        base_to_side_signed = float("nan")

    valid_faces = sum(int(obs[x].valid) for x in FACE_LABELS)
    fan_valid = sum(int(obs[x].valid) for x in FAN_LABELS)
    fan_w = wilson_product([K12, K23, K31], loop_step, normalize=False)
    boundary_w = wilson_product([KB, -K12, -K23, -K31], loop_step, normalize=False)
    fan_w_norm = wilson_product([K12, K23, K31], loop_step, normalize=True)
    boundary_w_norm = wilson_product([KB, -K12, -K23, -K31], loop_step, normalize=True)

    # A minimal fixed/signless J comparison inside the tetrahedron.  This is an
    # audit only; it must not be mistaken for a global J lock.
    js = [obs[x].J for x in FACE_LABELS if obs[x].J is not None]
    if len(js) >= 2:
        fixed_pairs = []
        pm_pairs = []
        for i in range(len(js)):
            for j in range(i + 1, len(js)):
                fixed_pairs.append(rel(js[i], js[j], False))
                pm_pairs.append(rel(js[i], js[j], True))
        Jfixed = mean(fixed_pairs)
        Jpm = mean(pm_pairs)
    else:
        Jfixed = float("nan")
        Jpm = float("nan")

    return {
        "tetra_kind": t.kind,
        "parent": int(t.parent),
        "level": int(t.level),
        "source": source_mode,
        "reduction": reduction,
        "identical_clone": int(identical_clone),
        "valid_faces": valid_faces,
        "fan_valid": fan_valid,
        "K_fan_mean": mean(obs[x].K_norm for x in FAN_LABELS),
        "K_base": obs["B123"].K_norm,
        "K_total_mean": mean(obs[x].K_norm for x in FACE_LABELS),
        "base_to_fan_ratio": obs["B123"].K_norm / (mean(obs[x].K_norm for x in FAN_LABELS) + EPS),
        "fan_sum_rel": fro(fan_nat) / fan_norm,
        "boundary_sum_rel": fro(boundary) / all_norm,
        "boundary_gain_vs_fan": (fro(fan_nat) / fan_norm) - (fro(boundary) / all_norm),
        "axis_side_abs_cos": mean(side_pair_abs),
        "axis_side_signed_cos": mean(side_pair_signed),
        "axis_base_to_side_abs": base_to_side_abs,
        "axis_base_to_side_signed": base_to_side_signed,
        "axis_side_chirality": side_chiral,
        "axis_side_chirality_abs": abs(side_chiral) if np.isfinite(side_chiral) else float("nan"),
        "axis_base_side_chirality": base_side_chiral,
        "axis_base_side_chirality_abs": abs(base_side_chiral) if np.isfinite(base_side_chiral) else float("nan"),
        "axis_boundary_rel": nrm(oriented_axis_boundary) / (nrm(base_axis) + nrm(side_axis_sum) + EPS),
        "Jfixed": Jfixed,
        "Jpm": Jpm,
        "J2_mean": mean(obs[x].J2 for x in FACE_LABELS),
        "J2_fan_mean": mean(obs[x].J2 for x in FAN_LABELS),
        "complex_faces": sum(int(obs[x].complex) for x in FACE_LABELS),
        "complex_fan": sum(int(obs[x].complex) for x in FAN_LABELS),
        "fan_wilson": fan_w["norm"],
        "fan_wilson_skew": fan_w["skew"],
        "fan_wilson_complex": fan_w["complex"],
        "boundary_wilson": boundary_w["norm"],
        "boundary_wilson_skew": boundary_w["skew"],
        "boundary_wilson_complex": boundary_w["complex"],
        "fan_wilson_normed": fan_w_norm["norm"],
        "boundary_wilson_normed": boundary_w_norm["norm"],
        "first_mean": mean(obs[x].first for x in FACE_LABELS),
        "edge_mean": mean(obs[x].edge for x in FACE_LABELS),
    }


def aggregate(rows: List[dict], keys: List[str]) -> List[dict]:
    groups: Dict[Tuple, List[dict]] = {}
    for r in rows:
        groups.setdefault(tuple(r.get(k) for k in keys), []).append(r)
    metric_keys = [
        "valid_faces", "fan_valid", "K_fan_mean", "K_base", "K_total_mean", "base_to_fan_ratio",
        "fan_sum_rel", "boundary_sum_rel", "boundary_gain_vs_fan", "axis_side_abs_cos",
        "axis_side_signed_cos", "axis_base_to_side_abs", "axis_base_to_side_signed",
        "axis_side_chirality_abs", "axis_base_side_chirality_abs", "axis_boundary_rel",
        "Jfixed", "Jpm", "J2_mean", "J2_fan_mean", "complex_faces", "complex_fan",
        "fan_wilson", "fan_wilson_skew", "boundary_wilson", "boundary_wilson_skew",
        "fan_wilson_normed", "boundary_wilson_normed", "first_mean", "edge_mean",
    ]
    out: List[dict] = []
    for kt, gs in sorted(groups.items(), key=lambda kv: tuple(str(x) for x in kv[0])):
        row = {k: v for k, v in zip(keys, kt)}
        row["count"] = len(gs)
        for m in metric_keys:
            vals = [float(g.get(m, float("nan"))) for g in gs]
            row[m] = mean(vals)
            row[m + "_p95"] = perc(vals, 95)
        out.append(row)
    return out


def run_one(args: argparse.Namespace, max_level: int, out_dir: Path) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)
    all_rows: List[dict] = []
    for control in args.controls:
        model = build_model(control, max_level, args.mode)
        cells = build_cells(model, max_level)
        true_tetras = build_true_tetras(model, cells)
        if args.max_tetras and len(true_tetras) > args.max_tetras:
            true_tetras = true_tetras[:args.max_tetras]
        random_tetras = build_random_tetras(model, cells, min(len(true_tetras), args.random_tetras), args.seed) if args.random_tetras else []
        for tetra in true_tetras + random_tetras:
            for source in args.sources:
                for reduction in args.reductions:
                    all_rows.append({"control": control, **summarize_tetra(tetra, cells, source, reduction, args.min_omega, args.loop_step, identical_clone=False)})
                    if tetra.kind == "true_tetrahedron" and source == "live" and reduction == "full" and args.include_identical_clone:
                        all_rows.append({"control": control, **summarize_tetra(tetra, cells, source, reduction, args.min_omega, args.loop_step, identical_clone=True)})
    write_csv(out_dir / "tetrahedron_rows.csv", all_rows)
    summary = aggregate(all_rows, ["control", "tetra_kind", "source", "reduction", "identical_clone"])
    write_csv(out_dir / "tetrahedron_summary.csv", summary)
    by_level = aggregate(all_rows, ["control", "tetra_kind", "source", "reduction", "identical_clone", "level"])
    write_csv(out_dir / "tetrahedron_summary_by_level.csv", by_level)

    primary = [r for r in summary if r["control"] == "real_growth" and r["tetra_kind"] == "true_tetrahedron" and r["source"] == "live" and r["reduction"] == "full" and int(r["identical_clone"]) == 0]
    lines: List[str] = []
    lines.append("# CNNA tetrahedral boundary orientation closure")
    lines.append("")
    lines.append(f"max_level: {max_level}")
    lines.append(f"rows: {len(all_rows)}")
    lines.append("")
    lines.append("## Primary reading")
    if primary:
        p = primary[0]
        fields = ["count", "K_fan_mean", "K_base", "base_to_fan_ratio", "fan_sum_rel", "boundary_sum_rel", "boundary_gain_vs_fan", "axis_side_abs_cos", "axis_side_chirality_abs", "axis_base_side_chirality_abs", "Jfixed", "Jpm", "fan_wilson", "boundary_wilson", "fan_wilson_normed", "boundary_wilson_normed"]
        for f in fields:
            lines.append(f"- {f}: {p.get(f)}")
    lines.append("")
    lines.append("## Gate interpretation")
    lines.append("- `K_base/base_to_fan_ratio` tests whether the sibling base participates in the tetrahedral boundary.")
    lines.append("- `boundary_sum_rel < fan_sum_rel` would indicate base-assisted oriented boundary closure.")
    lines.append("- nonzero `axis_*_chirality_abs` would indicate genuine 3D/chiral orientation rather than parallel flat axes.")
    lines.append("- diagonal/trace/common-mean reductions should kill the noncommutative K carrier.")
    lines.append("- symmetrized birth should suppress the dynamical amplitude if the carrier is growth-asymmetry dependent.")
    (out_dir / "RESULTS_tetrahedral_boundary_orientation_closure.md").write_text("\n".join(lines) + "\n", encoding="utf-8")


def make_readme(pkg: Path) -> None:
    (pkg / "README.md").write_text("""# CNNA tetrahedral boundary orientation closure

This package tests whether the full local 3-simplex `parent + three children`
contains an oriented boundary / chirality / closure obstruction that is invisible
in the parent-fan side faces alone.

Run for the default quick scan:

```bash
python3 test_tetrahedral_boundary_orientation_closure.py --max-levels 5 6
```

Primary output directories are `tetrahedral_boundary_orientation_out_L5/` and
`tetrahedral_boundary_orientation_out_L6/`.
""", encoding="utf-8")
    (pkg / "NOTES.md").write_text("""# Notes

This is still a diagnostic. It does not derive a global complex structure, a
*-algebra, a C*-completion, GNS, or an AQFT net.

The main anti-smuggling controls are: diagonal/trace/common-mean reductions,
symmetrized birth, no-backreaction, random tetrahedra, and an identical-clone
zero control.
""", encoding="utf-8")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--max-levels", type=int, nargs="+", default=[5, 6])
    ap.add_argument("--mode", default="linear", choices=["linear", "log", "saturating"])
    ap.add_argument("--controls", nargs="+", default=["real_growth", "symmetrized_birth", "no_backreaction"])
    ap.add_argument("--sources", nargs="+", default=["live", "handoff", "aging"])
    ap.add_argument("--reductions", nargs="+", default=["full", "diagonal", "trace_scalar", "common_mean_diagonal"])
    ap.add_argument("--random-tetras", type=int, default=80)
    ap.add_argument("--max-tetras", type=int, default=0)
    ap.add_argument("--seed", type=int, default=12345)
    ap.add_argument("--min-omega", type=float, default=1e-12)
    ap.add_argument("--loop-step", type=float, default=0.04)
    ap.add_argument("--include-identical-clone", action="store_true", default=True)
    ap.add_argument("--out-prefix", default="tetrahedral_boundary_orientation_out")
    args = ap.parse_args()
    base = Path(__file__).resolve().parent
    for L in args.max_levels:
        run_one(args, int(L), base / f"{args.out_prefix}_L{L}")
    make_readme(base)
    zip_path = base / "tetrahedral_boundary_orientation_outputs.zip"
    if zip_path.exists():
        zip_path.unlink()
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
        for L in args.max_levels:
            out_dir = base / f"{args.out_prefix}_L{L}"
            for p in out_dir.rglob("*"):
                if p.is_file():
                    zf.write(p, p.relative_to(base))


if __name__ == "__main__":
    main()
