"""
CNNA / growing real complement network
Generated real operator-system closure diagnostic.

Purpose
-------
This diagnostic follows the Record/Live block adjoint test.  The previous test
showed that the immediate growth-visible reverse handoff family does not close
under the DtN block adjoint, even though the adjoint lies in a larger typed
rank-one envelope.

This test therefore builds the finite real operator system generated by the
actual longitudinal and transverse Record/Live block operators.  For a local
Double-History pair a,b it works on the two-cell block space

    X_ab = W_a ⊕ W_b,     W_p = B_p^record ⊕ B_p^live,     B_p = R^3.

The growth-produced generators are embedded as 12x12 real matrices:

    D_ab      = diag(L_a, L_b),
    N_ab^k   = off-diagonal handoff W_a -> W_b,
    N_ba^k   = off-diagonal handoff W_b -> W_a,
    I_ab      = identity.

The test closes the real linear span under words up to a finite degree
(default 1,2,3), then asks:

  1. Is the generated finite word-space stable under the block DtN adjoint?
  2. Is it stable, at this truncation, under one more multiplication by the
     growth generators?
  3. Does true growth behave differently from identical-history, symmetrized,
     no-backreaction, and random controls?

This is still not a J-test.  It is a pre-* gate: a real local operator-system
closure diagnostic.
"""

from __future__ import annotations

import argparse
import csv
import itertools
import random
import time
import zipfile
from pathlib import Path
from typing import Dict, Iterable, List, Tuple

import numpy as np

from record_live_block_base import (
    EPS,
    RealGrowth,
    LocalCell,
    build_cells,
    double_history_pairs,
    identical_pairs,
    random_pairs,
    block_handoff,
    block_longitudinal,
    block_metric,
    adjoint,
    fro,
    mean,
    std,
    perc,
    write_csv,
)


def matrix_rank_span(mats: List[np.ndarray], tol: float) -> int:
    good = [np.asarray(M, dtype=float).reshape(-1) for M in mats if np.linalg.norm(M) > tol]
    if not good:
        return 0
    A = np.stack(good, axis=1)
    s = np.linalg.svd(A, compute_uv=False)
    return int(np.sum(s > tol * max(A.shape) * max(float(s[0]), 1.0)))


def orthonormal_span(mats: List[np.ndarray], tol: float) -> Tuple[np.ndarray, List[np.ndarray], List[float]]:
    good = [np.asarray(M, dtype=float).reshape(-1) for M in mats if np.linalg.norm(M) > tol]
    if not good:
        return np.zeros((0, 0), dtype=float), [], []
    A = np.stack(good, axis=1)
    U, s, _ = np.linalg.svd(A, full_matrices=False)
    if len(s) == 0:
        return np.zeros((A.shape[0], 0), dtype=float), [], []
    keep = s > tol * max(A.shape) * max(float(s[0]), 1.0)
    Q = U[:, keep]
    dim = int(np.sqrt(A.shape[0]))
    basis = [Q[:, i].reshape(dim, dim) for i in range(Q.shape[1])]
    return Q, basis, [float(x) for x in s]


def residual_to_Q(M: np.ndarray, Q: np.ndarray) -> Tuple[float, float]:
    v = np.asarray(M, dtype=float).reshape(-1)
    n = float(np.linalg.norm(v))
    if n < EPS:
        return 0.0, 0.0
    if Q.size == 0 or Q.shape[1] == 0:
        return n, 1.0
    proj = Q @ (Q.T @ v)
    r = v - proj
    rn = float(np.linalg.norm(r))
    return rn, rn / (n + EPS)


def embed_diag(A: np.ndarray, B: np.ndarray) -> np.ndarray:
    Z = np.zeros_like(A)
    return np.block([[A, Z], [Z, B]])


def embed_ab(T: np.ndarray) -> np.ndarray:
    Z = np.zeros_like(T)
    return np.block([[Z, Z], [T, Z]])


def embed_ba(T: np.ndarray) -> np.ndarray:
    Z = np.zeros_like(T)
    return np.block([[Z, T], [Z, Z]])


def build_pair_generators(
    a: LocalCell,
    b: LocalCell,
    operator_mode: str,
    longitudinal_mode: str,
    generator_ports: str,
    include_projectors: bool,
    include_longitudinal_powers: bool,
) -> Tuple[List[np.ndarray], Dict[str, float]]:
    La = block_longitudinal(a, longitudinal_mode)
    Lb = block_longitudinal(b, longitudinal_mode)
    I6 = np.eye(6)
    Z6 = np.zeros((6, 6), dtype=float)
    I12 = np.eye(12)
    Pa = np.block([[I6, Z6], [Z6, Z6]])
    Pb = np.block([[Z6, Z6], [Z6, I6]])
    D = embed_diag(La, Lb)
    gens: List[np.ndarray] = [I12, D]
    if include_projectors:
        gens.extend([Pa, Pb])
    if include_longitudinal_powers:
        gens.append(D @ D)
    ports = [1, 2, 3]
    if generator_ports == "same_port_only":
        # caller still passes pair port through a/b grouping in rows; here all pairs
        # are evaluated with the same selected port stored in stats['selected_port'].
        raise ValueError("same_port_only handled by row_for_pair")
    for r in ports:
        Tab = block_handoff(a, b, r, operator_mode)[0]
        Tba = block_handoff(b, a, r, operator_mode)[0]
        gens.append(embed_ab(Tab))
        gens.append(embed_ba(Tba))
    stats = {
        "La_norm": fro(La),
        "Lb_norm": fro(Lb),
        "D_norm": fro(D),
        "seed_count": len(gens),
    }
    return gens, stats


def build_pair_generators_same_port(
    a: LocalCell,
    b: LocalCell,
    port: int,
    operator_mode: str,
    longitudinal_mode: str,
    include_projectors: bool,
    include_longitudinal_powers: bool,
) -> Tuple[List[np.ndarray], Dict[str, float]]:
    La = block_longitudinal(a, longitudinal_mode)
    Lb = block_longitudinal(b, longitudinal_mode)
    I6 = np.eye(6)
    Z6 = np.zeros((6, 6), dtype=float)
    I12 = np.eye(12)
    Pa = np.block([[I6, Z6], [Z6, Z6]])
    Pb = np.block([[Z6, Z6], [Z6, I6]])
    D = embed_diag(La, Lb)
    gens: List[np.ndarray] = [I12, D]
    if include_projectors:
        gens.extend([Pa, Pb])
    if include_longitudinal_powers:
        gens.append(D @ D)
    Tab = block_handoff(a, b, port, operator_mode)[0]
    Tba = block_handoff(b, a, port, operator_mode)[0]
    gens.append(embed_ab(Tab))
    gens.append(embed_ba(Tba))
    return gens, {"La_norm": fro(La), "Lb_norm": fro(Lb), "D_norm": fro(D), "seed_count": len(gens)}


def word_space(gens: List[np.ndarray], max_degree: int, tol: float, cap: int) -> Tuple[List[np.ndarray], Dict[str, float]]:
    # Build all generator words up to degree max_degree, compressing span after
    # every degree to keep the diagnostic finite and reproducible.
    words: List[np.ndarray] = [gens[0]] if gens else []
    current: List[np.ndarray] = [gens[0]] if gens else []
    all_mats: List[np.ndarray] = list(gens)
    degree_counts = {"degree_0_or_seed_count": len(all_mats)}
    prev_words = list(gens)
    for d in range(2, max_degree + 1):
        new_words: List[np.ndarray] = []
        for A in prev_words:
            for G in gens:
                new_words.append(A @ G)
                if len(new_words) >= cap:
                    break
            if len(new_words) >= cap:
                break
        all_mats.extend(new_words)
        degree_counts[f"degree_{d}_raw_words"] = len(new_words)
        Q, basis, _ = orthonormal_span(all_mats, tol)
        # Use current basis as prev_words for next degree to avoid exponential blowup.
        prev_words = basis[:cap]
        all_mats = basis[:cap]
        degree_counts[f"degree_{d}_span_dim"] = len(all_mats)
    Q, basis, svals = orthonormal_span(all_mats, tol)
    stats = dict(degree_counts)
    stats["word_space_dim"] = int(Q.shape[1]) if Q.size else 0
    stats["word_space_sval_max"] = max(svals, default=0.0)
    stats["word_space_sval_min_kept"] = min([x for x in svals if x > tol], default=0.0)
    return basis, stats


def block_pair_metric(a: LocalCell, b: LocalCell, metric_source: str, ridge: float) -> Tuple[np.ndarray, Dict[str, float]]:
    Ga, sa = block_metric(a, metric_source, ridge)
    Gb, sb = block_metric(b, metric_source, ridge)
    G = np.block([[Ga, np.zeros_like(Ga)], [np.zeros_like(Gb), Gb]])
    return G, {
        "metric_a_cond": sa["metric_cond"],
        "metric_b_cond": sb["metric_cond"],
        "metric_a_min_eig": sa["metric_min_eig"],
        "metric_b_min_eig": sb["metric_min_eig"],
        "metric_a_ridge_added": sa["metric_ridge_added"],
        "metric_b_ridge_added": sb["metric_ridge_added"],
    }


def star_relative_stats(basis: List[np.ndarray], Q: np.ndarray, G: np.ndarray) -> Dict[str, float]:
    if not basis:
        return {"star_basis_rel_mean": float("nan"), "star_basis_rel_max": float("nan"), "star_basis_rel_p95": float("nan")}
    rels = []
    for A in basis:
        Astar = adjoint(A, G, G)
        _, rel = residual_to_Q(Astar, Q)
        rels.append(rel)
    return {
        "star_basis_rel_mean": mean(rels),
        "star_basis_rel_std": std(rels),
        "star_basis_rel_p50": perc(rels, 50),
        "star_basis_rel_p95": perc(rels, 95),
        "star_basis_rel_max": max(rels, default=float("nan")),
        "star_basis_rel_lt_0p05_fraction": mean([float(x < 0.05) for x in rels]),
        "star_basis_rel_lt_0p25_fraction": mean([float(x < 0.25) for x in rels]),
    }


def seed_star_stats(gens: List[np.ndarray], Q: np.ndarray, G: np.ndarray) -> Dict[str, float]:
    rels = []
    for A in gens:
        Astar = adjoint(A, G, G)
        _, rel = residual_to_Q(Astar, Q)
        rels.append(rel)
    return {
        "star_seed_rel_mean": mean(rels),
        "star_seed_rel_p95": perc(rels, 95),
        "star_seed_rel_max": max(rels, default=float("nan")),
        "star_seed_rel_lt_0p05_fraction": mean([float(x < 0.05) for x in rels]),
        "star_seed_rel_lt_0p25_fraction": mean([float(x < 0.25) for x in rels]),
    }


def multiplication_stability_stats(gens: List[np.ndarray], basis: List[np.ndarray], Q: np.ndarray, sample_cap: int, seed: int) -> Dict[str, float]:
    if not basis or not gens:
        return {"mult_left_rel_mean": float("nan"), "mult_left_rel_max": float("nan")}
    pairs = [(i, j) for i in range(len(gens)) for j in range(len(basis))]
    rng = random.Random(seed)
    if len(pairs) > sample_cap:
        pairs = rng.sample(pairs, sample_cap)
    rels = []
    for i, j in pairs:
        _, rel = residual_to_Q(gens[i] @ basis[j], Q)
        rels.append(rel)
    return {
        "mult_left_samples": len(rels),
        "mult_left_rel_mean": mean(rels),
        "mult_left_rel_std": std(rels),
        "mult_left_rel_p50": perc(rels, 50),
        "mult_left_rel_p95": perc(rels, 95),
        "mult_left_rel_max": max(rels, default=float("nan")),
        "mult_left_rel_lt_0p05_fraction": mean([float(x < 0.05) for x in rels]),
        "mult_left_rel_lt_0p25_fraction": mean([float(x < 0.25) for x in rels]),
    }


def row_for_pair(
    a: LocalCell,
    b: LocalCell,
    port: int,
    control: str,
    pair_index: int,
    operator_mode: str,
    longitudinal_mode: str,
    metric_source: str,
    generator_ports: str,
    max_degree: int,
    ridge: float,
    tol: float,
    cap: int,
    sample_cap: int,
    seed: int,
    include_projectors: bool,
    include_longitudinal_powers: bool,
) -> Dict[str, float | str | int]:
    if generator_ports == "same_port_only":
        gens, gen_stats = build_pair_generators_same_port(a, b, port, operator_mode, longitudinal_mode, include_projectors, include_longitudinal_powers)
    else:
        gens, gen_stats = build_pair_generators(a, b, operator_mode, longitudinal_mode, generator_ports, include_projectors, include_longitudinal_powers)
    basis, wstats = word_space(gens, max_degree, tol, cap)
    Q, basis2, svals = orthonormal_span(basis, tol)
    G, mstats = block_pair_metric(a, b, metric_source, ridge)
    star_b = star_relative_stats(basis2, Q, G)
    star_s = seed_star_stats(gens, Q, G)
    mult = multiplication_stability_stats(gens, basis2, Q, sample_cap, seed + pair_index)
    Tab = block_handoff(a, b, port, operator_mode)[0]
    Tba = block_handoff(b, a, port, operator_mode)[0]
    La = block_longitudinal(a, longitudinal_mode)
    Lb = block_longitudinal(b, longitudinal_mode)
    Cab = Lb @ Tab - Tab @ La
    # embedded same-port objects, for direct visibility in generated span
    eTab = embed_ab(Tab)
    eTba = embed_ba(Tba)
    D = embed_diag(La, Lb)
    _, T_visible = residual_to_Q(eTab, Q)
    _, Tba_visible = residual_to_Q(eTba, Q)
    _, D_visible = residual_to_Q(D, Q)
    return {
        "control": control,
        "pair_index": pair_index,
        "operator_mode": operator_mode,
        "longitudinal_mode": longitudinal_mode,
        "metric_source": metric_source,
        "generator_ports": generator_ports,
        "max_degree": max_degree,
        "parent_a": a.parent,
        "parent_b": b.parent,
        "port": port,
        "level": a.level,
        "age_a": a.age,
        "age_b": b.age,
        "root_sector_a": a.root_sector,
        "root_sector_b": b.root_sector,
        "suffix": ".".join(map(str, a.suffix)),
        "T_norm": fro(Tab),
        "T_reverse_norm": fro(Tba),
        "C_norm": fro(Cab),
        "embedded_T_visible_relative": T_visible,
        "embedded_Tba_visible_relative": Tba_visible,
        "embedded_D_visible_relative": D_visible,
        **gen_stats,
        **wstats,
        "orthonormal_basis_dim": len(basis2),
        "span_sval_max": max(svals, default=0.0),
        "span_sval_min": min(svals, default=0.0) if svals else 0.0,
        **mstats,
        **star_b,
        **star_s,
        **mult,
    }


def summarize(rows: List[dict], label: str) -> dict:
    out: Dict[str, float | str | int] = {"label": label, "count": len(rows)}
    keys = [
        "T_norm", "T_reverse_norm", "C_norm", "word_space_dim", "orthonormal_basis_dim",
        "star_basis_rel_mean", "star_basis_rel_p50", "star_basis_rel_p95", "star_basis_rel_max",
        "star_basis_rel_lt_0p05_fraction", "star_basis_rel_lt_0p25_fraction",
        "star_seed_rel_mean", "star_seed_rel_p95", "star_seed_rel_max",
        "star_seed_rel_lt_0p05_fraction", "star_seed_rel_lt_0p25_fraction",
        "mult_left_rel_mean", "mult_left_rel_p50", "mult_left_rel_p95", "mult_left_rel_max",
        "mult_left_rel_lt_0p05_fraction", "mult_left_rel_lt_0p25_fraction",
        "metric_a_cond", "metric_b_cond", "metric_a_min_eig", "metric_b_min_eig",
    ]
    for k in keys:
        vals = [r[k] for r in rows if k in r]
        out[f"{k}_mean"] = mean(vals)
        out[f"{k}_std"] = std(vals)
        out[f"{k}_p50"] = perc(vals, 50)
        out[f"{k}_p95"] = perc(vals, 95)
        finite = [float(v) for v in vals if np.isfinite(float(v))]
        out[f"{k}_max"] = max(finite, default=float("nan"))
    out["fraction_nonzero_T"] = mean([float(r["T_norm"] > 1e-10) for r in rows]) if rows else 0.0
    out["fraction_nonzero_C"] = mean([float(r["C_norm"] > 1e-10) for r in rows]) if rows else 0.0
    return out


def truncate_pairs(pairs: List[Tuple[LocalCell, LocalCell, int]], max_pairs: int, seed: int) -> List[Tuple[LocalCell, LocalCell, int]]:
    if max_pairs <= 0 or len(pairs) <= max_pairs:
        return pairs
    rng = random.Random(seed)
    return rng.sample(pairs, max_pairs)


def run_case(case_name: str, model: RealGrowth, args: argparse.Namespace, seed_offset: int) -> Tuple[List[dict], List[dict]]:
    cells = build_cells(model, args.max_level)
    dh = truncate_pairs(double_history_pairs(cells), args.max_pairs_per_control, args.seed + seed_offset)
    ident = truncate_pairs(identical_pairs(cells), args.max_pairs_per_control, args.seed + seed_offset + 101)
    rand = random_pairs(cells, min(args.max_pairs_per_control if args.max_pairs_per_control > 0 else len(dh), max(1, len(dh))), args.seed + seed_offset + 202)
    pair_sets = [
        ("double_history_suffix_quotient", dh),
        ("identical_history_control", ident),
        ("random_same_level_port_baseline", rand),
    ]
    all_rows: List[dict] = []
    summaries: List[dict] = []
    for operator_mode in args.operator_modes:
        for longitudinal_mode in args.longitudinal_modes:
            for metric_source in args.metric_sources:
                for generator_ports in args.generator_ports:
                    for deg in args.degrees:
                        for control, pairs in pair_sets:
                            label = f"{case_name}:{control}:{operator_mode}:{longitudinal_mode}:{metric_source}:{generator_ports}:degree{deg}"
                            rows = [
                                row_for_pair(
                                    a, b, port,
                                    f"{case_name}:{control}",
                                    i,
                                    operator_mode,
                                    longitudinal_mode,
                                    metric_source,
                                    generator_ports,
                                    deg,
                                    args.ridge,
                                    args.tol,
                                    args.word_cap,
                                    args.mult_sample_cap,
                                    args.seed + seed_offset,
                                    args.include_projectors,
                                    args.include_longitudinal_powers,
                                )
                                for i, (a, b, port) in enumerate(pairs)
                            ]
                            all_rows.extend(rows)
                            summaries.append(summarize(rows, label))
    summaries.insert(0, {
        "label": f"{case_name}:meta",
        "count": len(cells),
        "completed_cells": len(cells),
        "double_history_pairs_used": len(dh),
        "identical_pairs_used": len(ident),
        "random_pairs_used": len(rand),
        "nodes": len(model.nodes),
    })
    return all_rows, summaries


def find_summary(summaries: List[dict], label: str) -> dict | None:
    for s in summaries:
        if s.get("label") == label:
            return s
    return None


def write_results(path: Path, args: argparse.Namespace, summaries: List[dict]) -> None:
    primary_label = f"real_growth:double_history_suffix_quotient:triangular_handoff:triangular_record_live:record_live_block:all_ports:degree{max(args.degrees)}"
    primary = find_summary(summaries, primary_label)
    ident = find_summary(summaries, f"real_growth:identical_history_control:triangular_handoff:triangular_record_live:record_live_block:all_ports:degree{max(args.degrees)}")
    sym = find_summary(summaries, f"symmetrized_birth:double_history_suffix_quotient:triangular_handoff:triangular_record_live:record_live_block:all_ports:degree{max(args.degrees)}")
    nobr = find_summary(summaries, f"no_backreaction:double_history_suffix_quotient:triangular_handoff:triangular_record_live:record_live_block:all_ports:degree{max(args.degrees)}")
    rand = find_summary(summaries, f"real_growth:random_same_level_port_baseline:triangular_handoff:triangular_record_live:record_live_block:all_ports:degree{max(args.degrees)}")
    lines: List[str] = []
    lines.append("# RESULTS: generated real operator-system closure")
    lines.append("")
    lines.append("## Status")
    lines.append("")
    lines.append("This is not a J-test. It tests whether the finite real operator space generated by growth-produced Record/Live longitudinal and transverse block operators is stable under the DtN block adjoint and finite multiplication closure.")
    lines.append("")
    lines.append("## Parameters")
    lines.append("")
    lines.append(f"- max_level: `{args.max_level}`")
    lines.append(f"- degrees: `{', '.join(map(str, args.degrees))}`")
    lines.append(f"- max_pairs_per_control: `{args.max_pairs_per_control}`")
    lines.append(f"- word_cap: `{args.word_cap}`")
    lines.append(f"- mult_sample_cap: `{args.mult_sample_cap}`")
    lines.append(f"- include_projectors: `{args.include_projectors}`")
    lines.append(f"- include_longitudinal_powers: `{args.include_longitudinal_powers}`")
    lines.append("")
    lines.append("## Primary gate")
    lines.append("")
    lines.append(f"Primary label: `{primary_label}`")
    if primary:
        for k, name in [
            ("count", "rows"),
            ("orthonormal_basis_dim_mean", "mean generated span dimension"),
            ("T_norm_mean", "mean ||T||"),
            ("C_norm_mean", "mean ||C||"),
            ("star_basis_rel_mean_mean", "mean basis-adjoint residual"),
            ("star_basis_rel_p95_mean", "mean p95 basis-adjoint residual"),
            ("star_basis_rel_lt_0p25_fraction_mean", "mean fraction basis-adjoint residual < 0.25"),
            ("star_seed_rel_mean_mean", "mean seed-adjoint residual"),
            ("star_seed_rel_lt_0p25_fraction_mean", "mean fraction seed-adjoint residual < 0.25"),
            ("mult_left_rel_mean_mean", "mean one-more-product residual"),
            ("mult_left_rel_lt_0p25_fraction_mean", "mean fraction one-more-product residual < 0.25"),
            ("metric_a_cond_mean", "mean metric condition number"),
        ]:
            v = primary.get(k, float("nan"))
            if isinstance(v, (int, np.integer)):
                lines.append(f"- {name}: `{int(v)}`")
            elif isinstance(v, float):
                lines.append(f"- {name}: `{v:.12g}`")
            else:
                lines.append(f"- {name}: `{v}`")
    else:
        lines.append("Primary label not found.")
    lines.append("")
    lines.append("## Controls")
    lines.append("")
    for name, s in [("identical-history", ident), ("symmetrized-birth", sym), ("no-backreaction", nobr), ("random same-level/port", rand)]:
        if not s:
            continue
        lines.append(f"### {name}")
        lines.append(f"- rows: `{int(s['count'])}`")
        lines.append(f"- mean generated span dimension: `{s['orthonormal_basis_dim_mean']:.12g}`")
        lines.append(f"- mean ||T||: `{s['T_norm_mean']:.12g}`")
        lines.append(f"- mean ||C||: `{s['C_norm_mean']:.12g}`")
        lines.append(f"- mean basis-adjoint residual: `{s['star_basis_rel_mean_mean']:.12g}`")
        lines.append(f"- mean seed-adjoint residual: `{s['star_seed_rel_mean_mean']:.12g}`")
        lines.append(f"- mean one-more-product residual: `{s['mult_left_rel_mean_mean']:.12g}`")
        lines.append("")
    lines.append("## Interpretation")
    lines.append("")
    lines.append("A positive pre-* gate would require small adjoint residuals for the generated word-space and small one-more-product residuals. Large adjoint residuals mean that finite products of the current L/T block generators still do not produce a growth-visible real *-closed operator system.")
    lines.append("")
    lines.append("If closure fails, the next step is not J extraction but generator enrichment: include additional history transport/intertwiner generators or derive a richer boundary-history space. If closure succeeds, the next gate is a real *-algebra candidate and only afterwards a J²=-I test.")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--max-level", type=int, default=5)
    ap.add_argument("--mode", choices=["linear", "log", "saturating"], default="linear")
    ap.add_argument("--out", type=Path, default=Path("generated_real_operator_system_out_L5"))
    ap.add_argument("--seed", type=int, default=20260621)
    ap.add_argument("--max-pairs-per-control", type=int, default=360)
    ap.add_argument("--degrees", nargs="+", type=int, default=[1, 2, 3])
    ap.add_argument("--word-cap", type=int, default=180)
    ap.add_argument("--mult-sample-cap", type=int, default=250)
    ap.add_argument("--tol", type=float, default=1e-9)
    ap.add_argument("--ridge", type=float, default=1e-10)
    ap.add_argument("--operator-modes", nargs="+", default=["triangular_handoff"], choices=["triangular_handoff", "triangular_aging", "diagonal_record_live", "offdiag_handoff_only"])
    ap.add_argument("--longitudinal-modes", nargs="+", default=["triangular_record_live"], choices=["triangular_record_live", "triangular_record_handoff", "diagonal_record_live", "live_duplicate"])
    ap.add_argument("--metric-sources", nargs="+", default=["record_live_block"], choices=["record_live_block", "record_live_plus_aging_coupled", "live_duplicate_block"])
    ap.add_argument("--generator-ports", nargs="+", default=["all_ports"], choices=["all_ports", "same_port_only"])
    ap.add_argument("--include-projectors", action="store_true", default=True)
    ap.add_argument("--no-projectors", dest="include_projectors", action="store_false")
    ap.add_argument("--include-longitudinal-powers", action="store_true", default=True)
    ap.add_argument("--no-longitudinal-powers", dest="include_longitudinal_powers", action="store_false")
    args = ap.parse_args()

    t0 = time.time()
    args.out.mkdir(parents=True, exist_ok=True)

    cases = []
    real = RealGrowth(mode=args.mode, growth_rule="sequential")
    real.grow(args.max_level)
    cases.append(("real_growth", real))
    nobr = RealGrowth(mode=args.mode, growth_rule="sequential", br_ancestor=0.0, br_sibling=0.0)
    nobr.grow(args.max_level)
    cases.append(("no_backreaction", nobr))
    sym = RealGrowth(mode=args.mode, growth_rule="symmetrized_birth")
    sym.grow(args.max_level)
    cases.append(("symmetrized_birth", sym))

    all_rows: List[dict] = []
    all_summaries: List[dict] = []
    for idx, (name, model) in enumerate(cases):
        rows, summaries = run_case(name, model, args, idx * 1000)
        all_rows.extend(rows)
        all_summaries.extend(summaries)
        write_csv(args.out / f"pair_table_{name}.csv", rows)
        write_csv(args.out / f"summary_table_{name}.csv", summaries)

    write_csv(args.out / "pair_table_all.csv", all_rows)
    write_csv(args.out / "summary_table_all.csv", all_summaries)
    write_results(args.out / "RESULTS_generated_real_operator_system_closure.md", args, all_summaries)
    (args.out / "SUMMARY.txt").write_text(
        "\n".join([
            "CNNA generated real operator-system closure diagnostic",
            f"max_level={args.max_level}",
            f"degrees={args.degrees}",
            f"rows={len(all_rows)} summaries={len(all_summaries)}",
            f"elapsed_sec={time.time() - t0:.3f}",
            "Primary file: RESULTS_generated_real_operator_system_closure.md",
        ]) + "\n",
        encoding="utf-8",
    )

    zip_path = args.out.with_suffix(".zip")
    with zipfile.ZipFile(zip_path, "w", compression=zipfile.ZIP_DEFLATED) as z:
        z.write(Path(__file__), Path(__file__).name)
        z.write(Path(__file__).with_name("record_live_block_base.py"), "record_live_block_base.py")
        for p in args.out.rglob("*"):
            if p.is_file():
                z.write(p, p.relative_to(args.out.parent))
    print("wrote", args.out)
    print("wrote", zip_path)


if __name__ == "__main__":
    main()
