"""
CNNA / growing real complement network
Port-resolved rank-one adjoint-closure diagnostic.

Purpose
-------
This diagnostic follows the real local adjoint candidate test.  It keeps the
full 3-port DtN boundary space of each completed local cell instead of
compressing immediately to a nearly collinear 2D Env/UV role plane.

The question is whether the growth-generated longitudinal/transverse operator
system is closer to closure under the canonical adjoint defined by the full
port-resolved Schur/DtN energy pairing.

For a completed local parent p, the local boundary space is

    B_p = R^{children(p)} = R^3.

The local metric/pairing G_p is the positive Schur/DtN live, record, or mixed
matrix on these ports, with a tiny numerical ridge when necessary.

For a double-history pair a,b and port k, the transverse rank-one handoff map is

    T_ab^k : B_a -> B_b,
    T_ab^k x = delta_ab^k * x_k,

where delta_ab^k is the full 3-port difference of the selected DtN row/germ
between two histories identified by the suffix quotient.  This keeps the full
port vector and only uses a port selector on the source side.

The candidate adjoint is

    (T_ab^k)^* = G_a^{-1} (T_ab^k)^T G_b.

The nontrivial gate is whether this adjoint is visible in the reverse operator
system generated by the reverse handoffs T_ba^r and reverse mixed-composition
defects.

Growth rule
-----------
The growth is inherited from the previous dynamic birth tests:
- ternary children are born sequentially;
- child k senses parent-line + older siblings;
- the newborn immediately backreacts on parent-line and older siblings;
- descendant shell-loads keep aging older local cells.

Limitations
-----------
Numerical diagnostic only.  No physical i, no J, no J^2=-I, no C*-norm, no
GNS representation, and no AQFT net are derived here.
"""

from __future__ import annotations

import argparse
import csv
import itertools
import math
import random
import time
import zipfile
from collections import defaultdict
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Tuple

import numpy as np

EPS = 1e-12


def mean(xs: Iterable[float]) -> float:
    vals = [float(x) for x in xs if np.isfinite(float(x))]
    return float(np.mean(vals)) if vals else float("nan")


def std(xs: Iterable[float]) -> float:
    vals = [float(x) for x in xs if np.isfinite(float(x))]
    return float(np.std(vals)) if vals else float("nan")


def perc(xs: Iterable[float], q: float) -> float:
    vals = [float(x) for x in xs if np.isfinite(float(x))]
    return float(np.percentile(vals, q)) if vals else float("nan")


def fro(M: np.ndarray) -> float:
    return float(np.linalg.norm(M, ord="fro"))


def nrm(v: np.ndarray) -> float:
    return float(np.linalg.norm(v))


def unit(v: np.ndarray) -> np.ndarray:
    n = nrm(v)
    if n < EPS:
        return np.zeros_like(v, dtype=float)
    return np.asarray(v, dtype=float) / n


def offdiag_norm(M: np.ndarray) -> float:
    A = np.asarray(M, dtype=float).copy()
    np.fill_diagonal(A, 0.0)
    return fro(A)


def write_csv(path: Path, rows: List[dict]) -> None:
    if not rows:
        path.write_text("", encoding="utf-8")
        return
    keys = sorted({k for r in rows for k in r.keys()})
    with path.open("w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=keys)
        w.writeheader()
        w.writerows(rows)


def residual_to_span(M: np.ndarray, basis: List[np.ndarray]) -> Tuple[float, float, List[float]]:
    b = np.asarray(M, dtype=float).reshape(-1)
    n = float(np.linalg.norm(b))
    if n < EPS:
        return 0.0, 0.0, []
    good = [np.asarray(B, dtype=float).reshape(-1) for B in basis if np.linalg.norm(B) > EPS]
    if not good:
        return n, 1.0, []
    A = np.stack(good, axis=1)
    coeffs, *_ = np.linalg.lstsq(A, b, rcond=None)
    r = b - A @ coeffs
    rn = float(np.linalg.norm(r))
    return rn, rn / (n + EPS), [float(c) for c in coeffs]


@dataclass
class Node:
    id: int
    parent: Optional[int]
    level: int
    birth_order: int
    birth_time: int
    birth_g: float
    g: float
    children: List[int] = field(default_factory=list)


class RealGrowth:
    def __init__(
        self,
        *,
        branching: int = 3,
        mode: str = "linear",
        growth_rule: str = "sequential",
        base: float = 1.0,
        alpha_env: float = 0.22,
        ancestor_env_decay: float = 0.55,
        br_ancestor: float = 0.045,
        br_sibling: float = 0.035,
        shell_normalized: bool = True,
    ):
        if branching != 3:
            raise ValueError("this diagnostic currently assumes ternary local cells")
        if mode not in {"linear", "log", "saturating"}:
            raise ValueError("mode must be linear, log, or saturating")
        if growth_rule not in {"sequential", "symmetrized_birth"}:
            raise ValueError("growth_rule must be sequential or symmetrized_birth")
        self.b = branching
        self.mode = mode
        self.growth_rule = growth_rule
        self.base = base
        self.alpha_env = alpha_env
        self.ancestor_env_decay = ancestor_env_decay
        self.br_ancestor = br_ancestor
        self.br_sibling = br_sibling
        self.shell_normalized = shell_normalized
        self.nodes: Dict[int, Node] = {}
        self.local_w: Dict[int, Dict[Tuple[int, int], float]] = defaultdict(lambda: defaultdict(float))
        self.record_completion_matrix: Dict[int, np.ndarray] = {}
        self.live_completion_matrix: Dict[int, np.ndarray] = {}
        self.completion_level: Dict[int, int] = {}
        self.completion_child_g: Dict[int, np.ndarray] = {}
        self.completion_ancestor_env: Dict[int, float] = {}
        self.completion_desc_loads: Dict[int, np.ndarray] = {}
        self.desc_shell_load_by_node: Dict[int, float] = defaultdict(float)
        self.next_id = 0
        self.t = 0
        root = self._new_node(None, 0, 0, 1.0)
        self.root = root.id

    def _new_node(self, parent: Optional[int], level: int, birth_order: int, birth_g: float) -> Node:
        n = Node(self.next_id, parent, level, birth_order, self.t, birth_g, birth_g)
        self.nodes[n.id] = n
        self.next_id += 1
        if parent is not None:
            self.nodes[parent].children.append(n.id)
        return n

    def kernel_value(self, d: int) -> float:
        if not self.shell_normalized:
            return 1.0 / (d * d)
        return 1.0 / ((self.b ** (d - 1)) * d * d)

    def parent_line(self, parent: int) -> List[int]:
        line: List[int] = []
        cur: Optional[int] = parent
        while cur is not None:
            line.append(cur)
            cur = self.nodes[cur].parent
        return line

    def ancestor_env_load(self, parent: int) -> float:
        env = 0.0
        for d, a in enumerate(self.parent_line(parent), start=1):
            env += self.nodes[a].g * (self.ancestor_env_decay ** (d - 1))
        return env

    def birth_env_load(self, parent: int, older: List[int]) -> float:
        if self.growth_rule == "symmetrized_birth":
            return self.ancestor_env_load(parent)
        env = self.ancestor_env_load(parent)
        for s in older:
            env += self.nodes[s].g
        return env

    def child_g_from_env(self, env: float) -> float:
        if self.mode == "linear":
            return self.base + self.alpha_env * env
        if self.mode == "log":
            return self.base + self.alpha_env * math.log1p(env)
        return self.base + self.alpha_env * (env / (1.0 + env))

    def add_child(self, parent: int, order: int) -> int:
        self.t += 1
        older = list(self.nodes[parent].children)
        env = self.birth_env_load(parent, older)
        bg = self.child_g_from_env(env)
        child = self._new_node(parent, self.nodes[parent].level + 1, order, bg)
        if self.growth_rule == "sequential":
            for s in older:
                i = self.nodes[s].birth_order
                j = order
                self.local_w[parent][(i, j)] += self.alpha_env * self.nodes[s].g / (env + EPS) * bg
            for s in older:
                i = order
                j = self.nodes[s].birth_order
                delta = self.br_sibling * bg
                self.nodes[s].g += delta
                self.local_w[parent][(i, j)] += delta
        else:
            if len(self.nodes[parent].children) == self.b:
                ch = self.child_ids_ordered(parent)
                gmean = float(np.mean([self.nodes[c].g for c in ch]))
                w = self.alpha_env * gmean / (self.ancestor_env_load(parent) + EPS) * gmean
                for i in range(1, self.b + 1):
                    for j in range(1, self.b + 1):
                        if i != j:
                            self.local_w[parent][(i, j)] = w
        for d, a in enumerate(self.parent_line(parent), start=1):
            kd = self.kernel_value(d)
            self.nodes[a].g += self.br_ancestor * bg * kd
            self.desc_shell_load_by_node[a] += bg * kd
        if len(self.nodes[parent].children) == self.b:
            self._snapshot_completion(parent)
        return child.id

    def grow_one_level(self, frontier: List[int]) -> List[int]:
        new_frontier: List[int] = []
        for p in frontier:
            for k in range(1, self.b + 1):
                new_frontier.append(self.add_child(p, k))
        return new_frontier

    def grow(self, max_level: int) -> None:
        frontier = [self.root]
        for _ in range(1, max_level + 1):
            frontier = self.grow_one_level(frontier)

    def completed_parent_ids(self) -> List[int]:
        return [n.id for n in self.nodes.values() if len(n.children) == self.b]

    def child_ids_ordered(self, parent: int) -> List[int]:
        ch = list(self.nodes[parent].children)
        ch.sort(key=lambda c: self.nodes[c].birth_order)
        return ch

    def child_g_vector(self, parent: int) -> np.ndarray:
        return np.array([self.nodes[c].g for c in self.child_ids_ordered(parent)], dtype=float)

    def child_descendant_loads(self, parent: int) -> np.ndarray:
        return np.array([self.desc_shell_load_by_node.get(c, 0.0) for c in self.child_ids_ordered(parent)], dtype=float)

    def local_record_matrix(self, parent: int) -> Optional[np.ndarray]:
        if len(self.nodes[parent].children) != self.b:
            return None
        M = np.zeros((3, 3), dtype=float)
        w = self.local_w[parent]
        for i in range(1, 4):
            for j in range(1, 4):
                if i != j:
                    M[j - 1, i - 1] = w.get((i, j), 0.0)
        return M

    def live_replay_matrix(self, parent: int) -> Optional[np.ndarray]:
        if len(self.nodes[parent].children) != self.b:
            return None
        g = self.child_g_vector(parent)
        ancestor_env = self.ancestor_env_load(parent)
        M = np.zeros((3, 3), dtype=float)
        if self.growth_rule == "symmetrized_birth":
            w = self.alpha_env * float(np.mean(g)) / (ancestor_env + EPS) * float(np.mean(g))
            for i in range(3):
                for j in range(3):
                    if i != j:
                        M[j, i] = w
            return M
        for i in range(1, 4):
            for j in range(1, 4):
                if i == j:
                    continue
                source = g[i - 1]
                target = g[j - 1]
                if i < j:
                    prefix = ancestor_env + float(np.sum(g[: j - 1]))
                    M[j - 1, i - 1] = self.alpha_env * source / (prefix + EPS) * target
                else:
                    M[j - 1, i - 1] = self.br_sibling * source
        return M

    def _snapshot_completion(self, parent: int) -> None:
        if parent in self.completion_level:
            return
        R = self.local_record_matrix(parent)
        L = self.live_replay_matrix(parent)
        if R is None or L is None:
            return
        self.record_completion_matrix[parent] = R.copy()
        self.live_completion_matrix[parent] = L.copy()
        self.completion_level[parent] = self.nodes[parent].level + 1
        self.completion_child_g[parent] = self.child_g_vector(parent).copy()
        self.completion_ancestor_env[parent] = self.ancestor_env_load(parent)
        self.completion_desc_loads[parent] = self.child_descendant_loads(parent).copy()


def sym_response(M: np.ndarray) -> np.ndarray:
    C = 0.5 * (M + M.T)
    C = np.maximum(C, 0.0)
    np.fill_diagonal(C, 0.0)
    return C


def dtn_decomposition(
    child_g: np.ndarray,
    ancestor_env: float,
    directed_response: np.ndarray,
    descendant_loads: np.ndarray,
    *,
    eta_sibling: float = 0.35,
    eta_descendant_shunt: float = 0.08,
    eta_env_shunt: float = 0.18,
) -> dict:
    g = np.maximum(np.asarray(child_g, dtype=float), EPS)
    desc = np.maximum(np.asarray(descendant_loads, dtype=float), 0.0)
    C = eta_sibling * sym_response(directed_response)
    port_shunt = eta_descendant_shunt * desc
    core_shunt = max(eta_env_shunt * float(ancestor_env), EPS)
    D_env = np.diag(g) - np.outer(g, g) / (float(np.sum(g)) + core_shunt)
    D_sib = np.zeros((3, 3), dtype=float)
    for i in range(3):
        for j in range(i + 1, 3):
            c = max(float(C[i, j]), 0.0)
            D_sib[i, i] += c
            D_sib[j, j] += c
            D_sib[i, j] -= c
            D_sib[j, i] -= c
    D_uv = np.diag(port_shunt)
    D_total = D_env + D_sib + D_uv
    uv_port_mass = g + port_shunt
    env_row = np.sum(D_env, axis=1)
    return {
        "D_total": 0.5 * (D_total + D_total.T),
        "D_env": 0.5 * (D_env + D_env.T),
        "D_sib": 0.5 * (D_sib + D_sib.T),
        "D_uv": D_uv,
        "env_vec": env_row,
        "uv_vec": uv_port_mass,
        "core_shunt": core_shunt,
        "port_shunt": port_shunt,
    }


def address(model: RealGrowth, node_id: int) -> Tuple[int, ...]:
    out: List[int] = []
    cur = node_id
    while model.nodes[cur].parent is not None:
        out.append(int(model.nodes[cur].birth_order))
        cur = model.nodes[cur].parent
    return tuple(reversed(out))


class LocalCell:
    def __init__(self, model: RealGrowth, parent: int, max_level: int):
        self.model = model
        self.parent = int(parent)
        self.level = int(model.nodes[parent].level)
        self.completion_level = int(model.completion_level[parent])
        self.age = int(max_level - self.completion_level)
        self.address = address(model, parent)
        self.root_sector = int(self.address[0]) if self.address else 0
        self.suffix = tuple(self.address[1:]) if self.address else tuple()
        R = model.record_completion_matrix[parent]
        L0 = model.live_completion_matrix[parent]
        L1 = model.live_replay_matrix(parent)
        if L1 is None:
            raise ValueError("missing live replay")
        self.R_dir = R.copy()
        self.L0_dir = L0.copy()
        self.L1_dir = L1.copy()
        self.record = dtn_decomposition(
            model.completion_child_g[parent],
            model.completion_ancestor_env[parent],
            self.R_dir,
            model.completion_desc_loads[parent],
        )
        self.live0 = dtn_decomposition(
            model.completion_child_g[parent],
            model.completion_ancestor_env[parent],
            self.L0_dir,
            model.completion_desc_loads[parent],
        )
        self.live1 = dtn_decomposition(
            model.child_g_vector(parent),
            model.ancestor_env_load(parent),
            self.L1_dir,
            model.child_descendant_loads(parent),
        )
        self.aging = self.live1["D_total"] - self.live0["D_total"]
        self.handoff = self.live1["D_total"] - self.record["D_total"]

    def matrix_for_source(self, source_mode: str) -> np.ndarray:
        if source_mode == "record":
            return self.record["D_total"].copy()
        if source_mode == "live":
            return self.live1["D_total"].copy()
        if source_mode == "aging":
            return self.aging.copy()
        if source_mode == "handoff":
            return self.handoff.copy()
        raise ValueError(f"unknown source_mode {source_mode}")

    def port_germ(self, port: int, source_mode: str) -> np.ndarray:
        return self.matrix_for_source(source_mode)[port - 1, :].copy()

    def longitudinal_operator(self, longitudinal_mode: str) -> np.ndarray:
        if longitudinal_mode == "dtn_live":
            return self.live1["D_total"].copy()
        if longitudinal_mode == "dtn_handoff":
            return self.handoff.copy()
        if longitudinal_mode == "directed_live":
            return self.L1_dir.copy()
        if longitudinal_mode == "directed_handoff":
            return self.L1_dir - self.R_dir
        raise ValueError(f"unknown longitudinal_mode {longitudinal_mode}")


def build_cells(model: RealGrowth, max_level: int) -> Dict[int, LocalCell]:
    cells: Dict[int, LocalCell] = {}
    for p in model.completed_parent_ids():
        if p in model.completion_level:
            cells[p] = LocalCell(model, p, max_level)
    return cells


def double_history_pairs(cells: Dict[int, LocalCell]) -> List[Tuple[LocalCell, LocalCell, int]]:
    groups: Dict[Tuple[int, Tuple[int, ...], int], List[LocalCell]] = defaultdict(list)
    for c in cells.values():
        if c.level < 1:
            continue
        for port in (1, 2, 3):
            groups[(c.level, c.suffix, port)].append(c)
    pairs = []
    for key, gs in sorted(groups.items(), key=lambda kv: (kv[0][0], kv[0][2], kv[0][1])):
        roots = {g.root_sector for g in gs}
        if len(gs) < 2 or len(roots) < 2:
            continue
        port = int(key[2])
        for a, b in itertools.combinations(gs, 2):
            if a.root_sector != b.root_sector:
                pairs.append((a, b, port))
    return pairs


def identical_pairs(cells: Dict[int, LocalCell]) -> List[Tuple[LocalCell, LocalCell, int]]:
    out = []
    for c in cells.values():
        if c.level < 1:
            continue
        for port in (1, 2, 3):
            out.append((c, c, port))
    return out


def random_pairs(cells: Dict[int, LocalCell], n: int, seed: int) -> List[Tuple[LocalCell, LocalCell, int]]:
    rng = random.Random(seed)
    buckets: Dict[Tuple[int, int], List[LocalCell]] = defaultdict(list)
    for c in cells.values():
        if c.level >= 1:
            for port in (1, 2, 3):
                buckets[(c.level, port)].append(c)
    keys = [k for k, v in buckets.items() if len(v) >= 2]
    out = []
    attempts = 0
    while len(out) < n and attempts < max(2000, 40 * n):
        attempts += 1
        level, port = rng.choice(keys)
        a, b = rng.sample(buckets[(level, port)], 2)
        if a.suffix == b.suffix:
            continue
        out.append((a, b, port))
    return out


def metric(cell: LocalCell, metric_source: str, ridge: float) -> Tuple[np.ndarray, dict]:
    if metric_source == "live":
        G = cell.live1["D_total"].copy()
    elif metric_source == "record":
        G = cell.record["D_total"].copy()
    elif metric_source == "record_plus_live":
        G = 0.5 * (cell.record["D_total"] + cell.live1["D_total"])
    else:
        raise ValueError(f"unknown metric_source {metric_source}")
    G = 0.5 * (G + G.T)
    eig0 = np.linalg.eigvalsh(G)
    scale = max(float(np.trace(G)) / 3.0, 1.0)
    ridge_added = 0.0
    if float(eig0[0]) <= ridge * scale:
        ridge_added = ridge * scale - float(eig0[0]) + ridge * scale
        G = G + ridge_added * np.eye(3)
    eig = np.linalg.eigvalsh(G)
    cond = float(eig[-1] / max(eig[0], EPS))
    return G, {
        "metric_min_eig": float(eig[0]),
        "metric_max_eig": float(eig[-1]),
        "metric_cond": cond,
        "metric_ridge_added": ridge_added,
        "metric_original_min_eig": float(eig0[0]),
    }


def adjoint(A: np.ndarray, G_dom: np.ndarray, G_cod: np.ndarray) -> np.ndarray:
    return np.linalg.solve(G_dom, A.T @ G_cod)


def rank_one_handoff(a: LocalCell, b: LocalCell, port: int, source_mode: str) -> Tuple[np.ndarray, dict]:
    delta = b.port_germ(port, source_mode) - a.port_germ(port, source_mode)
    e = np.zeros(3, dtype=float)
    e[port - 1] = 1.0
    T = np.outer(delta, e)
    return T, {
        "delta_norm": nrm(delta),
        "delta_sum": float(np.sum(delta)),
        "delta_port_component": float(delta[port - 1]),
        "delta_offport_norm": nrm(np.delete(delta, port - 1)),
        "T_norm": fro(T),
        "T_rank_numeric": int(np.linalg.matrix_rank(T, tol=1e-10)),
    }


def reverse_basis(a: LocalCell, b: LocalCell, source_mode: str, source_ports: str) -> List[np.ndarray]:
    ports = [1, 2, 3]
    ops: List[np.ndarray] = []
    if source_ports == "same":
        raise ValueError("same port must be handled outside")
    if source_ports == "all_ports":
        for r in ports:
            T, _ = rank_one_handoff(b, a, r, source_mode)
            ops.append(T)
        return ops
    if source_ports == "rank_one_envelope":
        for r in ports:
            delta = a.port_germ(r, source_mode) - b.port_germ(r, source_mode)
            for j in ports:
                e = np.zeros(3, dtype=float)
                e[j - 1] = 1.0
                ops.append(np.outer(delta, e))
        return ops
    raise ValueError(f"unknown source_ports {source_ports}")


def row_for_pair(
    a: LocalCell,
    b: LocalCell,
    port: int,
    source_mode: str,
    longitudinal_mode: str,
    metric_source: str,
    control: str,
    pair_index: int,
    ridge: float,
) -> dict:
    T_ab, tstats = rank_one_handoff(a, b, port, source_mode)
    T_ba, _ = rank_one_handoff(b, a, port, source_mode)
    La = a.longitudinal_operator(longitudinal_mode)
    Lb = b.longitudinal_operator(longitudinal_mode)
    C_ab = Lb @ T_ab - T_ab @ La
    C_ba = La @ T_ba - T_ba @ Lb
    Ga, ga_stats = metric(a, metric_source, ridge)
    Gb, gb_stats = metric(b, metric_source, ridge)
    T_star = adjoint(T_ab, Ga, Gb)
    C_star = adjoint(C_ab, Ga, Gb)
    L_star = adjoint(La, Ga, Ga)
    T_star_star = adjoint(T_star, Gb, Ga)
    same_res, same_rel, same_coeff = residual_to_span(T_star, [T_ba])
    all_res, all_rel, all_coeff = residual_to_span(T_star, reverse_basis(a, b, source_mode, "all_ports"))
    env_res, env_rel, env_coeff = residual_to_span(T_star, reverse_basis(a, b, source_mode, "rank_one_envelope"))
    C_same_res, C_same_rel, _ = residual_to_span(C_star, [C_ba])
    C_basis = []
    for r in (1, 2, 3):
        Tr, _ = rank_one_handoff(b, a, r, source_mode)
        C_basis.append(La @ Tr - Tr @ Lb)
    C_all_res, C_all_rel, _ = residual_to_span(C_star, C_basis)
    I = np.eye(3)
    L_span_res, L_span_rel, _ = residual_to_span(L_star, [I, La, La @ La])
    denom_comp = fro(Lb @ T_ab) + fro(T_ab @ La) + EPS
    row = {
        "control": control,
        "pair_index": pair_index,
        "source_mode": source_mode,
        "longitudinal_mode": longitudinal_mode,
        "metric_source": metric_source,
        "parent_a": a.parent,
        "parent_b": b.parent,
        "port": port,
        "level": a.level,
        "age_a": a.age,
        "age_b": b.age,
        "root_sector_a": a.root_sector,
        "root_sector_b": b.root_sector,
        "address_a": ".".join(map(str, a.address)),
        "address_b": ".".join(map(str, b.address)),
        "suffix": ".".join(map(str, a.suffix)),
        "T_norm": fro(T_ab),
        "C_norm": fro(C_ab),
        "C_rel": fro(C_ab) / denom_comp,
        "L_a_norm": fro(La),
        "L_b_norm": fro(Lb),
        "L_star_norm": fro(L_star),
        "L_star_span_I_L_L2_residual": L_span_res,
        "L_star_span_I_L_L2_relative": L_span_rel,
        "T_star_norm": fro(T_star),
        "T_star_same_port_reverse_residual": same_res,
        "T_star_same_port_reverse_relative": same_rel,
        "T_star_all_ports_reverse_residual": all_res,
        "T_star_all_ports_reverse_relative": all_rel,
        "T_star_rank_one_envelope_residual": env_res,
        "T_star_rank_one_envelope_relative": env_rel,
        "T_star_involution_defect": fro(T_star_star - T_ab) / (fro(T_ab) + EPS),
        "C_star_norm": fro(C_star),
        "C_star_same_port_reverse_residual": C_same_res,
        "C_star_same_port_reverse_relative": C_same_rel,
        "C_star_all_ports_reverse_residual": C_all_res,
        "C_star_all_ports_reverse_relative": C_all_rel,
        "same_port_coeff0": same_coeff[0] if same_coeff else float("nan"),
        "all_ports_coeff_norm": float(np.linalg.norm(all_coeff)) if all_coeff else float("nan"),
        "rank_one_envelope_coeff_norm": float(np.linalg.norm(env_coeff)) if env_coeff else float("nan"),
        "metric_a_min_eig": ga_stats["metric_min_eig"],
        "metric_a_cond": ga_stats["metric_cond"],
        "metric_a_ridge_added": ga_stats["metric_ridge_added"],
        "metric_b_min_eig": gb_stats["metric_min_eig"],
        "metric_b_cond": gb_stats["metric_cond"],
        "metric_b_ridge_added": gb_stats["metric_ridge_added"],
    }
    row.update(tstats)
    return row


def summarize(rows: List[dict], label: str) -> dict:
    out = {"label": label, "count": len(rows)}
    keys = [
        "T_norm", "C_norm", "C_rel", "L_star_span_I_L_L2_relative",
        "T_star_same_port_reverse_relative", "T_star_all_ports_reverse_relative",
        "T_star_rank_one_envelope_relative", "T_star_involution_defect",
        "C_star_same_port_reverse_relative", "C_star_all_ports_reverse_relative",
        "metric_a_cond", "metric_a_min_eig", "metric_a_ridge_added",
        "delta_norm", "delta_offport_norm",
    ]
    for k in keys:
        vals = [r[k] for r in rows if k in r]
        out[f"{k}_mean"] = mean(vals)
        out[f"{k}_std"] = std(vals)
        out[f"{k}_p50"] = perc(vals, 50)
        out[f"{k}_p95"] = perc(vals, 95)
        finite = [float(v) for v in vals if np.isfinite(float(v))]
        out[f"{k}_max"] = max(finite, default=float("nan"))
    out["fraction_nonzero_T"] = mean([float(r["T_norm"] > 1e-10) for r in rows]) if rows else 0.0
    out["fraction_nonzero_C"] = mean([float(r["C_norm"] > 1e-10) for r in rows]) if rows else 0.0
    out["fraction_Tstar_all_ports_rel_lt_0p25"] = mean([float(r["T_star_all_ports_reverse_relative"] < 0.25) for r in rows]) if rows else 0.0
    out["fraction_Tstar_envelope_rel_lt_0p25"] = mean([float(r["T_star_rank_one_envelope_relative"] < 0.25) for r in rows]) if rows else 0.0
    out["fraction_Cstar_all_ports_rel_lt_0p25"] = mean([float(r["C_star_all_ports_reverse_relative"] < 0.25) for r in rows]) if rows else 0.0
    return out


def run_case(
    case_name: str,
    model: RealGrowth,
    max_level: int,
    source_modes: List[str],
    longitudinal_modes: List[str],
    metric_sources: List[str],
    random_n: int,
    seed: int,
    ridge: float,
) -> Tuple[List[dict], List[dict]]:
    cells = build_cells(model, max_level)
    dh = double_history_pairs(cells)
    ident = identical_pairs(cells)
    rand = random_pairs(cells, min(random_n, max(1, len(dh))), seed)
    pair_sets = [
        ("double_history_suffix_quotient", dh),
        ("identical_history_control", ident),
        ("random_same_level_port_baseline", rand),
    ]
    all_rows: List[dict] = []
    summaries: List[dict] = []
    for source_mode in source_modes:
        for longitudinal_mode in longitudinal_modes:
            for metric_source in metric_sources:
                for control, pairs in pair_sets:
                    rows = [
                        row_for_pair(a, b, port, source_mode, longitudinal_mode, metric_source, f"{case_name}:{control}", i, ridge)
                        for i, (a, b, port) in enumerate(pairs)
                    ]
                    all_rows.extend(rows)
                    summaries.append(summarize(rows, f"{case_name}:{control}:{source_mode}:{longitudinal_mode}:{metric_source}"))
    meta = {
        "label": f"{case_name}:meta",
        "count": len(cells),
        "completed_cells": len(cells),
        "double_history_pairs": len(dh),
        "identical_pairs": len(ident),
        "random_pairs": len(rand),
        "nodes": len(model.nodes),
    }
    summaries.insert(0, meta)
    return all_rows, summaries


def find_summary(summaries: List[dict], label: str) -> Optional[dict]:
    for s in summaries:
        if s.get("label") == label:
            return s
    return None


def write_results_md(path: Path, args: argparse.Namespace, summaries: List[dict]) -> None:
    primary_label = "real_growth:double_history_suffix_quotient:handoff:dtn_live:live"
    primary = find_summary(summaries, primary_label)
    ident = find_summary(summaries, "real_growth:identical_history_control:handoff:dtn_live:live")
    sym = find_summary(summaries, "symmetrized_birth:double_history_suffix_quotient:handoff:dtn_live:live")
    nobr = find_summary(summaries, "no_backreaction:double_history_suffix_quotient:handoff:dtn_live:live")
    rand = find_summary(summaries, "real_growth:random_same_level_port_baseline:handoff:dtn_live:live")
    lines: List[str] = []
    lines.append("# RESULTS: port-resolved rank-one adjoint closure")
    lines.append("")
    lines.append("## Status")
    lines.append("")
    lines.append("This is a port-resolved adjoint-closure diagnostic. It does not derive J and does not test J²=-I.")
    lines.append("It keeps the full 3-port DtN boundary space and tests whether rank-one transverse handoff maps generated by true growth close better under the full DtN-energy adjoint.")
    lines.append("")
    lines.append("## Parameters")
    lines.append("")
    lines.append(f"- max_level: `{args.max_level}`")
    lines.append(f"- conductance mode: `{args.mode}`")
    lines.append(f"- source modes: `{', '.join(args.source_modes)}`")
    lines.append(f"- longitudinal modes: `{', '.join(args.longitudinal_modes)}`")
    lines.append(f"- metric sources: `{', '.join(args.metric_sources)}`")
    lines.append(f"- ridge: `{args.ridge}`")
    lines.append(f"- random seed: `{args.seed}`")
    lines.append("")
    lines.append("## Primary gate")
    lines.append("")
    if primary:
        lines.append(f"- primary label: `{primary_label}`")
        lines.append(f"- rows: `{int(primary['count'])}`")
        lines.append(f"- mean T norm: `{primary['T_norm_mean']:.12g}`")
        lines.append(f"- mean mixed composition norm: `{primary['C_norm_mean']:.12g}`")
        lines.append(f"- mean mixed composition relative norm: `{primary['C_rel_mean']:.12g}`")
        lines.append(f"- mean T* same-port reverse residual: `{primary['T_star_same_port_reverse_relative_mean']:.12g}`")
        lines.append(f"- mean T* all-ports reverse residual: `{primary['T_star_all_ports_reverse_relative_mean']:.12g}`")
        lines.append(f"- mean T* rank-one-envelope residual: `{primary['T_star_rank_one_envelope_relative_mean']:.12g}`")
        lines.append(f"- mean C* same-port reverse residual: `{primary['C_star_same_port_reverse_relative_mean']:.12g}`")
        lines.append(f"- mean C* all-ports reverse residual: `{primary['C_star_all_ports_reverse_relative_mean']:.12g}`")
        lines.append(f"- fraction T* all-ports residual < 0.25: `{primary['fraction_Tstar_all_ports_rel_lt_0p25']:.6g}`")
        lines.append(f"- fraction T* envelope residual < 0.25: `{primary['fraction_Tstar_envelope_rel_lt_0p25']:.6g}`")
        lines.append(f"- fraction C* all-ports residual < 0.25: `{primary['fraction_Cstar_all_ports_rel_lt_0p25']:.6g}`")
        lines.append(f"- mean metric condition number: `{primary['metric_a_cond_mean']:.12g}`")
        lines.append(f"- mean metric min eigenvalue: `{primary['metric_a_min_eig_mean']:.12g}`")
    lines.append("")
    lines.append("## Controls")
    lines.append("")
    for name, s in [
        ("identical-history", ident),
        ("symmetrized-birth", sym),
        ("no-backreaction", nobr),
        ("random same-level/port", rand),
    ]:
        if not s:
            continue
        lines.append(f"### {name}")
        lines.append(f"- rows: `{int(s['count'])}`")
        lines.append(f"- mean T norm: `{s['T_norm_mean']:.12g}`")
        lines.append(f"- mean C norm: `{s['C_norm_mean']:.12g}`")
        lines.append(f"- mean T* all-ports reverse residual: `{s['T_star_all_ports_reverse_relative_mean']:.12g}`")
        lines.append(f"- mean C* all-ports reverse residual: `{s['C_star_all_ports_reverse_relative_mean']:.12g}`")
        lines.append(f"- mean metric condition number: `{s['metric_a_cond_mean']:.12g}`")
        lines.append("")
    lines.append("## Interpretation")
    lines.append("")
    lines.append("Compared with the earlier 2D role-plane adjoint test, this diagnostic asks whether the poor closure was caused by premature compression of the boundary data. A positive result would be a small T* residual against reverse port-resolved handoffs and a small C* residual against reverse mixed-defect spans.")
    lines.append("")
    lines.append("The rank-one-envelope residual is intentionally weaker than the all-ports reverse residual. If only the envelope closes, the full reverse operator system is still under-generated. If even the envelope fails, the current port germs are still insufficient for a *-closed real operator system.")
    lines.append("")
    lines.append("Next gate after positive closure: real *-operator-system closure under addition, multiplication, and adjoint. If closure remains weak: enrich the generated operators with record/live block matrices or keep higher-dimensional boundary history spaces before attempting J.")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--max-level", type=int, default=6)
    ap.add_argument("--mode", choices=["linear", "log", "saturating"], default="linear")
    ap.add_argument("--out", type=Path, default=Path("port_resolved_rank_one_adjoint_out_L6"))
    ap.add_argument("--seed", type=int, default=20260621)
    ap.add_argument("--random-n", type=int, default=3000)
    ap.add_argument("--ridge", type=float, default=1e-10)
    ap.add_argument("--source-modes", nargs="+", default=["handoff"], choices=["handoff", "aging", "live", "record"])
    ap.add_argument("--longitudinal-modes", nargs="+", default=["dtn_live", "directed_live"], choices=["dtn_live", "dtn_handoff", "directed_live", "directed_handoff"])
    ap.add_argument("--metric-sources", nargs="+", default=["live"], choices=["live", "record", "record_plus_live"])
    args = ap.parse_args()
    t0 = time.time()
    args.out.mkdir(parents=True, exist_ok=True)
    cases = []
    real = RealGrowth(mode=args.mode, growth_rule="sequential")
    real.grow(args.max_level)
    cases.append(("real_growth", real))
    nobr = RealGrowth(mode=args.mode, growth_rule="sequential", br_ancestor=0.0, br_sibling=0.0)
    nobr.grow(args.max_level)
    cases.append(("no_backreaction", nobr))
    sym = RealGrowth(mode=args.mode, growth_rule="symmetrized_birth")
    sym.grow(args.max_level)
    cases.append(("symmetrized_birth", sym))
    all_rows: List[dict] = []
    all_summaries: List[dict] = []
    for idx, (name, model) in enumerate(cases):
        rows, summaries = run_case(
            name,
            model,
            args.max_level,
            args.source_modes,
            args.longitudinal_modes,
            args.metric_sources,
            args.random_n,
            args.seed + idx,
            args.ridge,
        )
        all_rows.extend(rows)
        all_summaries.extend(summaries)
        write_csv(args.out / f"pair_table_{name}.csv", rows)
        write_csv(args.out / f"summary_table_{name}.csv", summaries)
    write_csv(args.out / "pair_table_all.csv", all_rows)
    write_csv(args.out / "summary_table_all.csv", all_summaries)
    write_results_md(args.out / "RESULTS_port_resolved_rank_one_adjoint_closure.md", args, all_summaries)
    summary = [
        "CNNA port-resolved rank-one adjoint closure diagnostic",
        f"max_level={args.max_level}",
        f"mode={args.mode}",
        f"rows={len(all_rows)} summaries={len(all_summaries)}",
        f"elapsed_sec={time.time() - t0:.3f}",
        "Primary file: RESULTS_port_resolved_rank_one_adjoint_closure.md",
    ]
    (args.out / "SUMMARY.txt").write_text("\n".join(summary) + "\n", encoding="utf-8")
    zip_path = args.out.with_suffix(".zip")
    with zipfile.ZipFile(zip_path, "w", compression=zipfile.ZIP_DEFLATED) as z:
        z.write(Path(__file__), Path(__file__).name)
        for p in args.out.rglob("*"):
            if p.is_file():
                z.write(p, p.relative_to(args.out.parent))
    print("wrote", args.out)
    print("wrote", zip_path)


if __name__ == "__main__":
    main()
