"""
CNNA / growing real complement network
Record/Live block adjoint-closure diagnostic.

Purpose
-------
This diagnostic follows the port-resolved rank-one adjoint-closure test.  The
previous test showed that the full 3-port live DtN metric is well-conditioned,
but that the growth-visible reverse live handoff system is not closed under the
DtN adjoint.  This test checks whether the missing adjoint directions become
visible when the local boundary state is typed as a Record/Live block space

    W_p = B_p^record ⊕ B_p^live,   B_p = R^3.

The test therefore keeps both the immutable completion record and the current
live boundary response in the same local operator space.

Primary block objects
---------------------
For each completed local parent p:

    G_p^R = record DtN energy metric,
    G_p^L = live DtN energy metric,
    G_p^W = diag(G_p^R, G_p^L).

The primary longitudinal operator is a lower-triangular block operator

    L_p = [[R_p, 0], [A_p, L_p^live]],

where A_p = L_p^live - L_p^completion is the aging response.  This encodes that
record data is not overwritten, while live response receives aging/backreaction.

For a double-history pair a,b and port k the primary transverse handoff is

    T_ab^k = [[T_R, 0], [T_H, T_L]],

where T_R uses record row/germ differences, T_L uses live row/germ differences,
and T_H uses handoff row/germ differences.  The upper-right block is zero: live
history does not rewrite immutable record history.

The canonical block adjoint candidate is

    (T_ab^k)^* = (G_a^W)^(-1) (T_ab^k)^T G_b^W.

The gate is whether T* and C* = (L_b T - T L_a)* are visible in the reverse
block handoff/defect operator system generated by true growth.

Growth rule
-----------
The growth is inherited from the dynamic birth tests:
- ternary children are born sequentially;
- child k senses parent-line + older siblings;
- the newborn immediately backreacts on parent-line and older siblings;
- descendant shell-loads keep aging older local cells.

Limitations
-----------
Numerical diagnostic only.  No physical i, no J, no J^2=-I, no C*-norm, no GNS
representation, and no AQFT net are derived here.
"""

from __future__ import annotations

import argparse
import csv
import itertools
import math
import random
import time
import zipfile
from collections import defaultdict
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Tuple

import numpy as np

EPS = 1e-12


def mean(xs: Iterable[float]) -> float:
    vals = [float(x) for x in xs if np.isfinite(float(x))]
    return float(np.mean(vals)) if vals else float("nan")


def std(xs: Iterable[float]) -> float:
    vals = [float(x) for x in xs if np.isfinite(float(x))]
    return float(np.std(vals)) if vals else float("nan")


def perc(xs: Iterable[float], q: float) -> float:
    vals = [float(x) for x in xs if np.isfinite(float(x))]
    return float(np.percentile(vals, q)) if vals else float("nan")


def fro(M: np.ndarray) -> float:
    return float(np.linalg.norm(M, ord="fro"))


def nrm(v: np.ndarray) -> float:
    return float(np.linalg.norm(v))


def unit(v: np.ndarray) -> np.ndarray:
    n = nrm(v)
    if n < EPS:
        return np.zeros_like(v, dtype=float)
    return np.asarray(v, dtype=float) / n


def offdiag_norm(M: np.ndarray) -> float:
    A = np.asarray(M, dtype=float).copy()
    np.fill_diagonal(A, 0.0)
    return fro(A)


def write_csv(path: Path, rows: List[dict]) -> None:
    if not rows:
        path.write_text("", encoding="utf-8")
        return
    keys = sorted({k for r in rows for k in r.keys()})
    with path.open("w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=keys)
        w.writeheader()
        w.writerows(rows)


def residual_to_span(M: np.ndarray, basis: List[np.ndarray]) -> Tuple[float, float, List[float]]:
    b = np.asarray(M, dtype=float).reshape(-1)
    n = float(np.linalg.norm(b))
    if n < EPS:
        return 0.0, 0.0, []
    good = [np.asarray(B, dtype=float).reshape(-1) for B in basis if np.linalg.norm(B) > EPS]
    if not good:
        return n, 1.0, []
    A = np.stack(good, axis=1)
    coeffs, *_ = np.linalg.lstsq(A, b, rcond=None)
    r = b - A @ coeffs
    rn = float(np.linalg.norm(r))
    return rn, rn / (n + EPS), [float(c) for c in coeffs]


@dataclass
class Node:
    id: int
    parent: Optional[int]
    level: int
    birth_order: int
    birth_time: int
    birth_g: float
    g: float
    children: List[int] = field(default_factory=list)


class RealGrowth:
    def __init__(
        self,
        *,
        branching: int = 3,
        mode: str = "linear",
        growth_rule: str = "sequential",
        base: float = 1.0,
        alpha_env: float = 0.22,
        ancestor_env_decay: float = 0.55,
        br_ancestor: float = 0.045,
        br_sibling: float = 0.035,
        shell_normalized: bool = True,
    ):
        if branching != 3:
            raise ValueError("this diagnostic currently assumes ternary local cells")
        if mode not in {"linear", "log", "saturating"}:
            raise ValueError("mode must be linear, log, or saturating")
        if growth_rule not in {"sequential", "symmetrized_birth"}:
            raise ValueError("growth_rule must be sequential or symmetrized_birth")
        self.b = branching
        self.mode = mode
        self.growth_rule = growth_rule
        self.base = base
        self.alpha_env = alpha_env
        self.ancestor_env_decay = ancestor_env_decay
        self.br_ancestor = br_ancestor
        self.br_sibling = br_sibling
        self.shell_normalized = shell_normalized
        self.nodes: Dict[int, Node] = {}
        self.local_w: Dict[int, Dict[Tuple[int, int], float]] = defaultdict(lambda: defaultdict(float))
        self.record_completion_matrix: Dict[int, np.ndarray] = {}
        self.live_completion_matrix: Dict[int, np.ndarray] = {}
        self.completion_level: Dict[int, int] = {}
        self.completion_child_g: Dict[int, np.ndarray] = {}
        self.completion_ancestor_env: Dict[int, float] = {}
        self.completion_desc_loads: Dict[int, np.ndarray] = {}
        self.desc_shell_load_by_node: Dict[int, float] = defaultdict(float)
        self.next_id = 0
        self.t = 0
        root = self._new_node(None, 0, 0, 1.0)
        self.root = root.id

    def _new_node(self, parent: Optional[int], level: int, birth_order: int, birth_g: float) -> Node:
        n = Node(self.next_id, parent, level, birth_order, self.t, birth_g, birth_g)
        self.nodes[n.id] = n
        self.next_id += 1
        if parent is not None:
            self.nodes[parent].children.append(n.id)
        return n

    def kernel_value(self, d: int) -> float:
        if not self.shell_normalized:
            return 1.0 / (d * d)
        return 1.0 / ((self.b ** (d - 1)) * d * d)

    def parent_line(self, parent: int) -> List[int]:
        line: List[int] = []
        cur: Optional[int] = parent
        while cur is not None:
            line.append(cur)
            cur = self.nodes[cur].parent
        return line

    def ancestor_env_load(self, parent: int) -> float:
        env = 0.0
        for d, a in enumerate(self.parent_line(parent), start=1):
            env += self.nodes[a].g * (self.ancestor_env_decay ** (d - 1))
        return env

    def birth_env_load(self, parent: int, older: List[int]) -> float:
        if self.growth_rule == "symmetrized_birth":
            return self.ancestor_env_load(parent)
        env = self.ancestor_env_load(parent)
        for s in older:
            env += self.nodes[s].g
        return env

    def child_g_from_env(self, env: float) -> float:
        if self.mode == "linear":
            return self.base + self.alpha_env * env
        if self.mode == "log":
            return self.base + self.alpha_env * math.log1p(env)
        return self.base + self.alpha_env * (env / (1.0 + env))

    def add_child(self, parent: int, order: int) -> int:
        self.t += 1
        older = list(self.nodes[parent].children)
        env = self.birth_env_load(parent, older)
        bg = self.child_g_from_env(env)
        child = self._new_node(parent, self.nodes[parent].level + 1, order, bg)
        if self.growth_rule == "sequential":
            for s in older:
                i = self.nodes[s].birth_order
                j = order
                self.local_w[parent][(i, j)] += self.alpha_env * self.nodes[s].g / (env + EPS) * bg
            for s in older:
                i = order
                j = self.nodes[s].birth_order
                delta = self.br_sibling * bg
                self.nodes[s].g += delta
                self.local_w[parent][(i, j)] += delta
        else:
            if len(self.nodes[parent].children) == self.b:
                ch = self.child_ids_ordered(parent)
                gmean = float(np.mean([self.nodes[c].g for c in ch]))
                w = self.alpha_env * gmean / (self.ancestor_env_load(parent) + EPS) * gmean
                for i in range(1, self.b + 1):
                    for j in range(1, self.b + 1):
                        if i != j:
                            self.local_w[parent][(i, j)] = w
        for d, a in enumerate(self.parent_line(parent), start=1):
            kd = self.kernel_value(d)
            self.nodes[a].g += self.br_ancestor * bg * kd
            self.desc_shell_load_by_node[a] += bg * kd
        if len(self.nodes[parent].children) == self.b:
            self._snapshot_completion(parent)
        return child.id

    def grow_one_level(self, frontier: List[int]) -> List[int]:
        new_frontier: List[int] = []
        for p in frontier:
            for k in range(1, self.b + 1):
                new_frontier.append(self.add_child(p, k))
        return new_frontier

    def grow(self, max_level: int) -> None:
        frontier = [self.root]
        for _ in range(1, max_level + 1):
            frontier = self.grow_one_level(frontier)

    def completed_parent_ids(self) -> List[int]:
        return [n.id for n in self.nodes.values() if len(n.children) == self.b]

    def child_ids_ordered(self, parent: int) -> List[int]:
        ch = list(self.nodes[parent].children)
        ch.sort(key=lambda c: self.nodes[c].birth_order)
        return ch

    def child_g_vector(self, parent: int) -> np.ndarray:
        return np.array([self.nodes[c].g for c in self.child_ids_ordered(parent)], dtype=float)

    def child_descendant_loads(self, parent: int) -> np.ndarray:
        return np.array([self.desc_shell_load_by_node.get(c, 0.0) for c in self.child_ids_ordered(parent)], dtype=float)

    def local_record_matrix(self, parent: int) -> Optional[np.ndarray]:
        if len(self.nodes[parent].children) != self.b:
            return None
        M = np.zeros((3, 3), dtype=float)
        w = self.local_w[parent]
        for i in range(1, 4):
            for j in range(1, 4):
                if i != j:
                    M[j - 1, i - 1] = w.get((i, j), 0.0)
        return M

    def live_replay_matrix(self, parent: int) -> Optional[np.ndarray]:
        if len(self.nodes[parent].children) != self.b:
            return None
        g = self.child_g_vector(parent)
        ancestor_env = self.ancestor_env_load(parent)
        M = np.zeros((3, 3), dtype=float)
        if self.growth_rule == "symmetrized_birth":
            w = self.alpha_env * float(np.mean(g)) / (ancestor_env + EPS) * float(np.mean(g))
            for i in range(3):
                for j in range(3):
                    if i != j:
                        M[j, i] = w
            return M
        for i in range(1, 4):
            for j in range(1, 4):
                if i == j:
                    continue
                source = g[i - 1]
                target = g[j - 1]
                if i < j:
                    prefix = ancestor_env + float(np.sum(g[: j - 1]))
                    M[j - 1, i - 1] = self.alpha_env * source / (prefix + EPS) * target
                else:
                    M[j - 1, i - 1] = self.br_sibling * source
        return M

    def _snapshot_completion(self, parent: int) -> None:
        if parent in self.completion_level:
            return
        R = self.local_record_matrix(parent)
        L = self.live_replay_matrix(parent)
        if R is None or L is None:
            return
        self.record_completion_matrix[parent] = R.copy()
        self.live_completion_matrix[parent] = L.copy()
        self.completion_level[parent] = self.nodes[parent].level + 1
        self.completion_child_g[parent] = self.child_g_vector(parent).copy()
        self.completion_ancestor_env[parent] = self.ancestor_env_load(parent)
        self.completion_desc_loads[parent] = self.child_descendant_loads(parent).copy()


def sym_response(M: np.ndarray) -> np.ndarray:
    C = 0.5 * (M + M.T)
    C = np.maximum(C, 0.0)
    np.fill_diagonal(C, 0.0)
    return C


def dtn_decomposition(
    child_g: np.ndarray,
    ancestor_env: float,
    directed_response: np.ndarray,
    descendant_loads: np.ndarray,
    *,
    eta_sibling: float = 0.35,
    eta_descendant_shunt: float = 0.08,
    eta_env_shunt: float = 0.18,
) -> dict:
    g = np.maximum(np.asarray(child_g, dtype=float), EPS)
    desc = np.maximum(np.asarray(descendant_loads, dtype=float), 0.0)
    C = eta_sibling * sym_response(directed_response)
    port_shunt = eta_descendant_shunt * desc
    core_shunt = max(eta_env_shunt * float(ancestor_env), EPS)
    D_env = np.diag(g) - np.outer(g, g) / (float(np.sum(g)) + core_shunt)
    D_sib = np.zeros((3, 3), dtype=float)
    for i in range(3):
        for j in range(i + 1, 3):
            c = max(float(C[i, j]), 0.0)
            D_sib[i, i] += c
            D_sib[j, j] += c
            D_sib[i, j] -= c
            D_sib[j, i] -= c
    D_uv = np.diag(port_shunt)
    D_total = D_env + D_sib + D_uv
    uv_port_mass = g + port_shunt
    env_row = np.sum(D_env, axis=1)
    return {
        "D_total": 0.5 * (D_total + D_total.T),
        "D_env": 0.5 * (D_env + D_env.T),
        "D_sib": 0.5 * (D_sib + D_sib.T),
        "D_uv": D_uv,
        "env_vec": env_row,
        "uv_vec": uv_port_mass,
        "core_shunt": core_shunt,
        "port_shunt": port_shunt,
    }


def address(model: RealGrowth, node_id: int) -> Tuple[int, ...]:
    out: List[int] = []
    cur = node_id
    while model.nodes[cur].parent is not None:
        out.append(int(model.nodes[cur].birth_order))
        cur = model.nodes[cur].parent
    return tuple(reversed(out))


class LocalCell:
    def __init__(self, model: RealGrowth, parent: int, max_level: int):
        self.model = model
        self.parent = int(parent)
        self.level = int(model.nodes[parent].level)
        self.completion_level = int(model.completion_level[parent])
        self.age = int(max_level - self.completion_level)
        self.address = address(model, parent)
        self.root_sector = int(self.address[0]) if self.address else 0
        self.suffix = tuple(self.address[1:]) if self.address else tuple()
        R = model.record_completion_matrix[parent]
        L0 = model.live_completion_matrix[parent]
        L1 = model.live_replay_matrix(parent)
        if L1 is None:
            raise ValueError("missing live replay")
        self.R_dir = R.copy()
        self.L0_dir = L0.copy()
        self.L1_dir = L1.copy()
        self.record = dtn_decomposition(
            model.completion_child_g[parent],
            model.completion_ancestor_env[parent],
            self.R_dir,
            model.completion_desc_loads[parent],
        )
        self.live0 = dtn_decomposition(
            model.completion_child_g[parent],
            model.completion_ancestor_env[parent],
            self.L0_dir,
            model.completion_desc_loads[parent],
        )
        self.live1 = dtn_decomposition(
            model.child_g_vector(parent),
            model.ancestor_env_load(parent),
            self.L1_dir,
            model.child_descendant_loads(parent),
        )
        self.aging = self.live1["D_total"] - self.live0["D_total"]
        self.handoff = self.live1["D_total"] - self.record["D_total"]

    def matrix_for_source(self, source_mode: str) -> np.ndarray:
        if source_mode == "record":
            return self.record["D_total"].copy()
        if source_mode == "live":
            return self.live1["D_total"].copy()
        if source_mode == "aging":
            return self.aging.copy()
        if source_mode == "handoff":
            return self.handoff.copy()
        raise ValueError(f"unknown source_mode {source_mode}")

    def port_germ(self, port: int, source_mode: str) -> np.ndarray:
        return self.matrix_for_source(source_mode)[port - 1, :].copy()

    def longitudinal_operator(self, longitudinal_mode: str) -> np.ndarray:
        if longitudinal_mode == "dtn_live":
            return self.live1["D_total"].copy()
        if longitudinal_mode == "dtn_handoff":
            return self.handoff.copy()
        if longitudinal_mode == "directed_live":
            return self.L1_dir.copy()
        if longitudinal_mode == "directed_handoff":
            return self.L1_dir - self.R_dir
        raise ValueError(f"unknown longitudinal_mode {longitudinal_mode}")


def build_cells(model: RealGrowth, max_level: int) -> Dict[int, LocalCell]:
    cells: Dict[int, LocalCell] = {}
    for p in model.completed_parent_ids():
        if p in model.completion_level:
            cells[p] = LocalCell(model, p, max_level)
    return cells


def double_history_pairs(cells: Dict[int, LocalCell]) -> List[Tuple[LocalCell, LocalCell, int]]:
    groups: Dict[Tuple[int, Tuple[int, ...], int], List[LocalCell]] = defaultdict(list)
    for c in cells.values():
        if c.level < 1:
            continue
        for port in (1, 2, 3):
            groups[(c.level, c.suffix, port)].append(c)
    pairs = []
    for key, gs in sorted(groups.items(), key=lambda kv: (kv[0][0], kv[0][2], kv[0][1])):
        roots = {g.root_sector for g in gs}
        if len(gs) < 2 or len(roots) < 2:
            continue
        port = int(key[2])
        for a, b in itertools.combinations(gs, 2):
            if a.root_sector != b.root_sector:
                pairs.append((a, b, port))
    return pairs


def identical_pairs(cells: Dict[int, LocalCell]) -> List[Tuple[LocalCell, LocalCell, int]]:
    out = []
    for c in cells.values():
        if c.level < 1:
            continue
        for port in (1, 2, 3):
            out.append((c, c, port))
    return out


def random_pairs(cells: Dict[int, LocalCell], n: int, seed: int) -> List[Tuple[LocalCell, LocalCell, int]]:
    rng = random.Random(seed)
    buckets: Dict[Tuple[int, int], List[LocalCell]] = defaultdict(list)
    for c in cells.values():
        if c.level >= 1:
            for port in (1, 2, 3):
                buckets[(c.level, port)].append(c)
    keys = [k for k, v in buckets.items() if len(v) >= 2]
    out = []
    attempts = 0
    while len(out) < n and attempts < max(2000, 40 * n):
        attempts += 1
        level, port = rng.choice(keys)
        a, b = rng.sample(buckets[(level, port)], 2)
        if a.suffix == b.suffix:
            continue
        out.append((a, b, port))
    return out


