name: Build manifest.json

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  manifest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create manifest.json (paths + sizes + sha)
        shell: bash
        run: |
          set -euo pipefail
          # Liste aller Dateien (Blobs) im Repo mit Modus, Typ, SHA, Größe, Pfad
          # Format: <mode> <type> <sha> <size>\t<path>
          git ls-tree -r --long HEAD \
          | awk '{
              mode=$1; type=$2; sha=$3; size=$4;
              # Pfad steht nach einem TAB
              idx = index($0, "\t");
              path = substr($0, idx+1);
              # Escape von doppelten Anführungszeichen im Pfad
              gsub(/\"/, "\\\"", path);
              printf("{\"path\":\"%s\",\"sha\":\"%s\",\"size\":%s,\"type\":\"%s\",\"mode\":\"%s\"}\n", path, sha, size, type, mode);
            }' \
          | jq -s 'sort_by(.path)' > manifest.json

      - name: Commit manifest if changed
        shell: bash
        run: |
          set -euo pipefail
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add manifest.json
          git diff --cached --quiet || git commit -m "Update manifest [skip ci]"
          git push
