name: Build manifest.json

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

permissions:
  contents: write  # <-- wichtig: erlaubt Commit des Manifests

jobs:
  manifest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Holt die komplette Baumstruktur per GitHub-API und erzeugt manifest.json ohne jq/awk
      - name: Generate manifest.json via GitHub API
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const owner = context.repo.owner;
            const repo  = context.repo.repo;

            // Referenz: aktueller Commit auf dem Default-Branch (main)
            // Alternative: explizit "heads/main"
            const ref = process.env.GITHUB_SHA;

            // Vollständiger Baum (rekursiv)
            const treeResp = await github.rest.git.getTree({
              owner, repo,
              tree_sha: ref,
              recursive: 'true'
            });

            const tree = treeResp.data.tree || [];

            // Nur Dateien (blobs) mit Pfad, SHA, Größe, Modus
            const blobs = tree
              .filter(it => it.type === 'blob')
              .map(it => ({
                path: it.path,
                sha:  it.sha,
                size: it.size ?? 0,
                type: 'blob',
                mode: it.mode
              }))
              .sort((a,b) => a.path.localeCompare(b.path));

            fs.writeFileSync('manifest.json', JSON.stringify(blobs, null, 2));
            core.info(`Wrote manifest.json with ${blobs.length} entries.`);

      - name: Commit manifest if changed
        shell: bash
        run: |
          set -euo pipefail
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add manifest.json
          if ! git diff --cached --quiet; then
            git commit -m "Update manifest [skip ci]"
            git push
          else
            echo "No changes in manifest.json"
          fi
