name: i18n-md (DE → EN/FR/ES)

on:
  push:
    paths:
      - "**/*.md"
  workflow_dispatch:

jobs:
  translate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Compute changed Markdown
        id: diff
        shell: bash
        run: |
          set -euo pipefail
          BASE="${{ github.event.before || '' }}"
          if [ -z "$BASE" ] || [ "$BASE" = "0000000000000000000000000000000000000000" ]; then
            git ls-files "*.md" > changed.txt || true
          else
            git diff --name-only "$BASE" "${{ github.sha }}" -- "**/*.md" > changed.txt || true
          fi
          echo "Changed Markdown files:"
          cat changed.txt || true
          echo "changed<<EOF" >> "$GITHUB_OUTPUT"
          cat changed.txt >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install minimal deps
        run: |
          npm --yes init -y
          npm pkg set type=module
          npm i unified@11 remark-parse@10 remark-gfm@4 unist-util-visit@5

      - name: Add translate script
        shell: bash
        run: |
          mkdir -p .github/scripts
          cat > .github/scripts/translate-md.mjs <<'JS'
          import fs from "fs";
          import path from "path";
          import { unified } from "unified";
          import remarkParse from "remark-parse";
          import remarkGfm from "remark-gfm";
          import { visit } from "unist-util-visit";

          const SOURCE_LANG = (process.env.SOURCE_LANG || "DE").toUpperCase();
          const TARGET_LANGS = (process.env.TARGET_LANGS || "en,fr,es").split(",").map(s=>s.trim()).filter(Boolean);
          const DEEPL_API_URL = process.env.DEEPL_API_URL || "https://api-free.deepl.com/v2/translate";
          const DEEPL_API_KEY = process.env.DEEPL_API_KEY || "";
          const CHANGED_LIST = (process.env.CHANGED || "").split(/\r?\n/).map(s=>s.trim()).filter(Boolean);

          const SKIP_DIRS = new Set([".git","node_modules",".github"]);
          const isMd = f => f.toLowerCase().endsWith(".md");

          // List all md for initial/full runs
          function listAllMd(dir="."){
            const out=[];
            for (const e of fs.readdirSync(dir,{withFileTypes:true})) {
              if (SKIP_DIRS.has(e.name)) continue;
              const p = path.join(dir, e.name);
              if (e.isDirectory()) out.push(...listAllMd(p));
              else if (isMd(p)) out.push(p);
            }
            return out;
          }

          function shouldTranslateFile(f, supLangs){
            if (!isMd(f)) return false;
            const re = new RegExp(`\\.(${supLangs.join("|")})\\.md$`, "i");
            if (re.test(f)) return false; // already a translated file
            const parts = f.split(path.sep);
            if (parts.some(p => SKIP_DIRS.has(p))) return false;
            return true;
          }

          // Protect math segments before Markdown/translate
          function protectMath(src){
            const map=[]; let i=0;
            const take = (m)=>{ const id=`§§M${i++}§§`; map.push({id,content:m}); return id; };
            let out=src;
            out=out.replace(/\$\$[\s\S]*?\$\$/g, m=>take(m));
            out=out.replace(/\\\[([\s\S]*?)\\\]/g, m=>take(m));
            out=out.replace(/\\\(([\s\S]*?)\\\)/g, m=>take(m));
            return {text: out, map};
          }
          function restoreMath(txt,map){
            let out=txt;
            for (const {id,content} of map) out=out.split(id).join(content);
            return out;
          }

          function collectTranslatableNodes(md){
            const tree = unified().use(remarkParse).use(remarkGfm).parse(md);
            const nodes=[];
            visit(tree, (node, index, parent) => {
              if (node.type !== "text") return;
              if (parent && ["code","inlineCode","html"].includes(parent.type)) return;
              const val = node.value;
              if (!val || !val.trim()) return;
              const pos = node.position || {};
              if (typeof pos.start?.offset !== "number" || typeof pos.end?.offset !== "number") return;
              nodes.push({start: pos.start.offset, end: pos.end.offset, text: val});
            });
            return nodes;
          }

          async function deeplBatch(texts, targetLang){
            if (!DEEPL_API_KEY) {
              console.log("[i18n] No DEEPL_API_KEY → skipping translation.");
              return [];
            }
            const results = [];
            const chunk = 40;
            for (let i=0;i<texts.length;i+=chunk){
              const part = texts.slice(i,i+chunk);
              const body = new URLSearchParams();
              body.set("auth_key", DEEPL_API_KEY);
              body.set("source_lang", SOURCE_LANG);
              body.set("target_lang", targetLang.toUpperCase());
              body.set("preserve_formatting","1");
              for (const t of part) body.append("text", t);
              const r = await fetch(DEEPL_API_URL, { method:"POST", headers:{ "Content-Type":"application/x-www-form-urlencoded" }, body });
              if (!r.ok) {
                const e = await r.text().catch(()=>r.statusText);
                throw new Error(`DeepL HTTP ${r.status}: ${e}`);
              }
              const json = await r.json();
              const trans = json.translations?.map(x=>x.text) || [];
              results.push(...trans);
            }
            return results;
          }

          async function translateFile(srcPath){
            const raw = fs.readFileSync(srcPath, "utf8");
            const {text: protectedText, map: mathMap} = protectMath(raw);
            const nodes = collectTranslatableNodes(protectedText);
            if (!nodes.length) return { wrote: [] };

            for (const L of TARGET_LANGS){
              const texts = nodes.map(n=>n.text);
              const outTexts = await deeplBatch(texts, L);
              if (DEEPL_API_KEY && outTexts.length !== texts.length) {
                throw new Error("Translation batch size mismatch");
              }
              // If no key, skip writing outputs for target languages
              if (!DEEPL_API_KEY) continue;

              let out = protectedText;
              const rep = nodes.map((n,i)=>({...n, newText: outTexts[i]})).sort((a,b)=> b.start - a.start);
              for (const r of rep) {
                out = out.slice(0, r.start) + r.newText + out.slice(r.end);
              }
              out = restoreMath(out, mathMap);

              const dstPath = srcPath.replace(/\.md$/i, `.${L}.md`);
              fs.mkdirSync(path.dirname(dstPath), {recursive:true});
              fs.writeFileSync(dstPath, out, "utf8");
              console.log("→", dstPath);
            }
            return { wrote: TARGET_LANGS };
          }

          (async()=>{
            const supLangs = TARGET_LANGS.map(x=>x.toLowerCase());
            const candidates = (CHANGED_LIST.length? CHANGED_LIST : listAllMd(".")).filter(f=>shouldTranslateFile(f, supLangs));

            if (!candidates.length) {
              console.log("[i18n] No Markdown files to translate.");
              return;
            }

            let hadError = false;
            for (const f of candidates) {
              try {
                await translateFile(f);
              } catch(e) {
                hadError = true;
                console.error("[i18n] Failed:", f, e.message);
              }
            }
            if (hadError) process.exit(1);
          })();
          JS

      - name: Run translation
        env:
          DEEPL_API_KEY: ${{ secrets.DEEPL_API_KEY }}
          DEEPL_API_URL: https://api-free.deepl.com/v2/translate
          SOURCE_LANG: DE
          TARGET_LANGS: en,fr,es
          CHANGED: ${{ steps.diff.outputs.changed }}
        run: node .github/scripts/translate-md.mjs

      - name: Commit translated files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "i18n: update translated markdown"
          file_pattern: "**/*.en.md **/*.fr.md **/*.es.md"
