name: Deploy GitHub Pages (ignore .md-only)

on:
  push:
    branches: [ main ]
    paths:
      - '**'           # include everything...
      - '!**/*.md'     # ...but ignore pure Markdown changes
  workflow_dispatch:

concurrency:
  group: pages
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # If you need a build step (e.g., npm build), add it here.
      # For a static site, we just upload the repo root.
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
